app/controllers/api/v1/lists_controller.rb, app/javascript/flavours/glitch/actions/lists.js, app/javascript/flavours/glitch/features/list_editor/components/edit_list_form.js, app/javascript/flavours/glitch/features/list_editor/index.js, app/javascript/flavours/glitch/features/list_timeline/index.js, app/javascript/flavours/glitch/reducers/list_editor.js, app/javascript/flavours/glitch/styles/components/index.scss, app/javascript/mastodon/actions/lists.js, app/javascript/mastodon/features/list_editor/components/edit_list_form.js, app/javascript/mastodon/features/list_editor/index.js, app/javascript/mastodon/features/list_timeline/index.js, app/javascript/mastodon/reducers/list_editor.js, app/javascript/styles/mastodon/components.scss, app/lib/feed_manager.rb, app/models/list.rb, app/serializers/rest/list_serializer.rb, db/migrate/20221125104951_add_is_exclusive_to_list.rb, db/schema.rb
Port of hometown [exclusive list feature](https://github.com/hometown-fork/hometown/wiki/Exclusive-lists)
TL;DR: Toots from accounts on exclusive lists won't show up on home tl.
You can change any list to an exclusive list by enabling the "Exclusive?" toggle in the edit list setting.
Based on 
- [Adding exlusive lists feature](https://github.com/hometown-fork/hometown/commit/bfc0fbab2c94dc134715f555edf793991da172a2)
- [Fix for exclusive lists not working](https://github.com/hometown-fork/hometown/commit/b2270fd37)
- [Fix isExclusive being reset when renaming list](https://github.com/hometown-fork/hometown/commit/de227c8b1a4c37ec03b1def064a5cc454cb867c7)
- [Support changing list replies policies from web UI](https://github.com/hometown-fork/hometown/commit/4f7fa085cb3ae373e3e30139f32088c461 …
=> Experimental: Add exclusive lists feature

app/controllers/admin/registration_filters_controller.rb, app/helpers/admin/action_logs_helper.rb, app/models/admin/action_log_filter.rb, app/models/form/admin_settings.rb, app/models/registration_filter.rb, app/models/user_invite_request.rb, app/policies/registration_filter_policy.rb, app/validators/invite_request_validator.rb, app/validators/regex_validator.rb, app/views/admin/registration_filters/_fields.html.haml, app/views/admin/registration_filters/_registration_filter.html.haml, app/views/admin/registration_filters/edit.html.haml, app/views/admin/registration_filters/index.html.haml, app/views/admin/registration_filters/new.html.haml, config/locales/en.yml, config/navigation.rb, config/routes.rb, config/settings.yml, db/migrate/20221127215222_create_registration_filters.rb, db/schema.rb, spec/controllers/admin/registration_filters_controller_spec.rb, spec/fabricators/registration_filter_fabricator.rb, spec/models/registration_filter_spec.rb, spec/policies/registration_filter_policy_spec.rb, spec/validators/invite_request_validator_spec.rb
Based on [7dd4502](https://github.com/mastodon/mastodon/pull/15275/commits/7dd4502df7ea66de4c5b7d8e418230d5dd97bcee), [e499cc8](https://github.com/mastodon/mastodon/pull/15275/commits/e499cc8301ee1d10053d131ab6a4814388874446)
Updated for 4.0.x
Enabled editing of filters without enabled approval mode.
Automatically deny creation of account request when invite text includes filtered keyword(s). Supports RegEx. 
Important:
This feature creates a new table and requires db migration.
=> Add account request text filer

app/javascript/flavours/glitch/features/account/components/featured_tags.js, app/javascript/mastodon/features/account/components/featured_tags.js
Basically reverts c9d3c7d63a3218e3e113435213b7f9e63feb68a1 and 23d367f544485eaeed888c707012a8282bbb5806
Featured tags on profiles are limited to 3 out of 10 which can be set.
The limit of 3 was imposed because it causes the nav panel to scroll, which is a non-issue since it also scrolls when adding multiple lists.
=> Remove limit of featured tags shown on profile

app/javascript/flavours/glitch/components/media_gallery.js, app/javascript/mastodon/components/media_gallery.js
This just adds a little indicator to the left bottom of images when alt-text is available.
Glitch:
Vanilla:
=> Add visual indicator that image has alt-text

app/lib/settings/scoped_settings.rb, app/models/form/admin_settings.rb, app/views/admin/settings/other/show.html.haml, config/locales-glitch/en.yml
Adds back the noindex admin setting to opt out users of search indexing by default.
Adds new admin setting to disclose application by default.
These setting are added as glitch specific settings and available in the `other` tab.
If you're running vanilla, you have to port the settings to a different tab and copy the translation strings to vanilla language files.
=> Add admin user setting override

app/helpers/application_helper.rb, app/javascript/flavours/glitch/styles/forms.scss, app/javascript/styles/mastodon/forms.scss, app/models/form/admin_settings.rb, app/models/site_upload.rb, app/presenters/instance_presenter.rb, app/serializers/initial_state_serializer.rb, app/views/admin/settings/branding/show.html.haml, app/views/layouts/application.html.haml, config/locales/simple_form.en.yml
I just want to spite top guy.
This feature adds a new setting to the branding settings, which allows upload of a custom favicon[^1].
The custom favicon replaces all default favicons[^2].
Used chaos.social favicon for testing.
[^1]: png, ico or svg recommended
[^2]: custom favicons are resized to the appropriate resolution, but this doesn't always work.
Images don't scale up and resizing the test svg failed for 1024x1024.
=> Experimental: Add setting to customise favicon

app/controllers/accounts_controller.rb, app/controllers/settings/preferences_controller.rb, app/lib/settings/scoped_settings.rb, app/lib/user_settings_decorator.rb, app/models/form/admin_settings.rb, app/models/user.rb, app/views/accounts/show.html.haml, app/views/admin/settings/discovery/show.html.haml, app/views/settings/preferences/other/show.html.haml, config/locales-glitch/en.yml, config/locales-glitch/simple_form.en.yml, config/settings.yml
Port of upstream/#2002
Adds a user option to disable RSS feed for public posts.
Lets admins set a default for users.
Converted to glitch-only setting.
Added a hint to the user setting.
The `discovery.rss` locale string is unnecessary, as it defaults to the locale string name, but included for good measure.
=> Add setting to disable RSS feed

app/views/admin/settings/discovery/show.html.haml, config/locales-glitch/en.yml, config/locales-glitch/simple_form.en.yml, config/locales/en.yml, config/locales/simple_form.en.yml
I made the mistake of editing vanilla locale files in various earlier commits.
While it's not that much of an issue with backend files, I want to avoid merge conflicts when pulling updates.
Glitch locales don't update that often, so merge conflicts will be rare.
Also in interest of best practices, I added the glitch-soc label to these settings, to make it clear these are not offered by vanilla.
Ideally I would have my own label, to also make it clear these settings are specific to this fork, but I'm still thinking about that.
localisation for de and nl will be added in a future PR.
(I could need help with nl, as mijn Nederlands is niet zo goed)
Contributions of other languages are welcome.
=> Move localisations to glitch

app/javascript/styles/mastodon/accounts.scss, app/javascript/styles/mastodon/forms.scss
glitch-soc label is missing styling when vanilla flavour is used.
This fixes that.
=> Add styling for glitch-soc label to vanilla flavour

app/javascript/flavours/glitch/actions/announcements.js, app/javascript/mastodon/actions/announcements.js
I had no idea, you can even react to announcements, which makes it even more strange that reacting to toots isn't implemented yet.
But hey, this fixes a 404 when reacting with: #️⃣
=> Fix being unable to react to announcements with keycap number sign emoji

app/javascript/flavours/glitch/features/account/components/header.js, app/javascript/flavours/glitch/locales/en.js, app/javascript/mastodon/features/account/components/header.js
I keep accidentally trying to follow locked accounts, because the little lock icon is easily overlooked.
This changes the text on the follow button to "Request follow" for locked accounts.
Adds a new translation key: `account.request_follow`
=> Replace "Follow" with "Request follow" for locked accounts

app/javascript/flavours/glitch/features/compose/components/publisher.js, app/javascript/flavours/glitch/initial_state.js, app/javascript/mastodon/features/compose/components/compose_form.js, app/javascript/mastodon/initial_state.js, app/models/form/admin_settings.rb, app/serializers/initial_state_serializer.rb, app/views/admin/settings/appearance/show.html.haml, config/locales-glitch/simple_form.en.yml, config/settings.yml
Port of upstream/#1945
Adds an admin setting to customise the text of the publish button.
This setting will apply to all languages.
=> Add setting to customize publish button text

app/javascript/flavours/glitch/components/media_gallery.js, app/javascript/flavours/glitch/components/status.js, app/javascript/flavours/glitch/containers/status_container.js, app/javascript/flavours/glitch/features/audio/index.js, app/javascript/flavours/glitch/features/status/components/detailed_status.js, app/javascript/flavours/glitch/features/status/index.js, app/javascript/flavours/glitch/features/ui/components/alttext_modal.js, app/javascript/flavours/glitch/features/ui/components/modal_root.js, app/javascript/flavours/glitch/features/video/index.js, app/javascript/flavours/glitch/locales/en.json, app/javascript/flavours/glitch/styles/components/media.scss, app/javascript/flavours/glitch/styles/components/modal.scss
Wraps labels in a div, so alt button shows next to gif label.
Adds new modal which opens by clicking "alt", which shows the alt-text.
Preview:
Modal:
Toots:
Detailed view:
Caveats:
~As seen in the last screenshot, the labels don't have the proper left spacing. I'm not sure why.~ Not introduced by these changes, upstream issue.
~The labels are bigger than default, but I think that's actually good.~ Nope, They have the same size.
Only thing I don't like about this is that the button on video and audio files looks misaligned while being aligned with the other buttons. I think this illusion is caused by the hide button/icon appearing to be smaller than it should be.
This was a huge PITA to get working.
=> Add alt-text modal

app/serializers/rest/featured_tag_serializer.rb
React throws an invalid prop error when viewing featured tags because statuses_count is expected to be a number, but it's serialised as a string.
~As it's an int in the database and react is expecting a number, this removes the string conversion.~
This removes the serialisation for statuses_count as it seems like it doesn't need to be serialised.
This should not have any negative side effects.
=> Remove serialisation of statuses_count

stylelint.config.js
These paths exist after running `yarn build:development`, `yarn build:production` or `bundle exec rspec`, which makes stylelint take over 10 minutes to evaluate as all css/scss files in those paths are checked unnecessarily.
=> Add additional paths to stylelint ignoreFiles

app/javascript/flavours/glitch/styles/admin.scss, app/javascript/flavours/glitch/styles/components/about.scss
Removes max-height from bios in profile directory.
Removes nowrap from domain blocks.
This was in custom CSS since v4, but I might as well make it part of the code base.
Before:
Profile directory:
Domain blocks:
After:
Profile directory:
Domain blocks:
=> Enhance domain blocks and profile directory CSS

app/javascript/flavours/glitch/styles/components/index.scss
Fixes an issue introduced in #10 which caused imports overwriting other rules in the file.
One result of this was that all buttons on modals had backgrounds applied.
I actually prefer this, so I will restore that behaviour in Fairy Floss.
Since the original change was introduced before Fairy Floss, I have to recheck it and some of the fixes might be redundant.
Oof.
=> Fix wrong rules applying for some elements

app/javascript/flavours/glitch/components/status.js, app/javascript/flavours/glitch/features/account_gallery/index.js
Follow up to #52 because I was doing something else and didn't realise I wasn't done yet.
Ran `yarn run test:lint:js --fix` this time
Discarded changes to files upstream also didn't modify.
=> Even more lint fixes

app/javascript/flavours/glitch/styles/components/columns.scss
Removes `contain: strict;` from empty-column-indicator.
Not sure what this hack fixed, but that version of Chrome isn't around anymore and it causes issues now.
Before:
(Advanced UI)
(Simple UI)
After:
(Advanced UI)
(Simple UI)
=> Remove `contain: strict;` from empty-column-indicator

app/javascript/flavours/glitch/features/account_timeline/index.js
Missing this attribute causes scrollTop to not work in simple UI.
=> Add missing `bindToDocument` attribute to account_timeline

app/javascript/flavours/glitch/features/account_gallery/index.js, app/javascript/flavours/glitch/features/followers/index.js, app/javascript/flavours/glitch/features/following/index.js
Follow-up to #59
Add missing `bindToDocument` attribute
Turns out: each of these is technically a different column.
=> Fix scrolling to top on accounts in simple UI

app/javascript/flavours/glitch/reducers/compose.js
Resets the language to the default language instead of keeping the language of the replied to toot when cancelling the reply.
Also adds eslint-disable comment for no-fallthrough.
=> Reset language to default when cancelling a reply

streaming/index.js
Every query to the streaming API now requires an access token with at least `read:statuses` scope, aside from notifications, which still needs `read:notifications`
This API is almost exclusively used by scrapers and legit clients should send a token anyway.
=> Remove public access to streaming API

app/javascript/flavours/glitch/styles/components/modal.scss, app/javascript/flavours/glitch/styles/components/status.scss
Adds background and slight padding to code blocks for better visibility.
Inspired by upstream/#2104
Advanced UI:
Simple UI:
=> Add background to code blocks

app/javascript/flavours/glitch/styles/polls.scss
This change didn't get applied in the last upstream merge for some reason.
Before:
After:
=> Fix poll input

streaming/index.js
Claire never disappoints.
Similar to #65, which worked quite well, but denying access without a token in general is the better solution than checking scopes. Going to keep that change though, because I have to check if it actually prevents all access.
Early merge because I don't want to wait for it.
=> Disable anonymous access to the streaming API

app/models/form/admin_settings.rb, app/models/trends/statuses.rb, app/views/admin/settings/discovery/show.html.haml, config/locales-glitch/en.yml, config/settings.yml
Makes toots with sensitive media attachments eligible to trend.
Enabled by default
=> Add option to allow toots with sensitive media to trend

app/javascript/flavours/glitch/features/compose/components/reply_indicator.jsx, app/javascript/flavours/glitch/locales/en.json, app/javascript/flavours/glitch/styles/components/compose_form.scss
Adds a translatable "Replying to:" text to the reply indicator.
Inspired by the oatstodon theme.
**Preview:**
=> Add "Replying to:" text to reply-indicator

app/javascript/flavours/glitch/styles/rich_text.scss
Missed this while merging upstream.
=> Fix color of code blocks in reply-indicator

app/javascript/flavours/glitch/styles/oatstodon.scss, app/javascript/flavours/glitch/styles/oatstodon/diff.scss, app/javascript/flavours/glitch/styles/oatstodon/variables.scss, app/javascript/skins/glitch/oatstodon/common.scss, app/javascript/skins/glitch/oatstodon/names.yml
Port of https://gist.github.com/oatmealine/8081dcc0e0cc4ae04491bcbc1f023f8a
Applied some changes:
- Changed color of icons in emoji-picker to be more readable
- Changed color of show more button
- Changed color of language dropdown
- Moved "Replying to:" to the frontend to offer translations
- Kept default background for inputs in admin interface
- Removed borders on grouped mentioned only toots
- Kept some borders in admin interface for better readability
- Kept backgrounds in admin interface
Known issues:
- "Replying to:" text will be missing and spacing will be a bit off without #77
**Screenshots**
WebUI:
Settings:
=> Add Oatstodon theme

app/javascript/flavours/glitch/components/status_content.jsx, app/javascript/flavours/glitch/features/compose/components/reply_indicator.jsx, app/javascript/flavours/glitch/utils/html.js
Ref #20
Moved highlightCode to `util/html.js`
=> SyntaxHighlight: Support highlighting in reply-indicator

app/javascript/flavours/glitch/features/community_timeline/components/column_settings.jsx, app/javascript/flavours/glitch/features/public_timeline/components/column_settings.jsx, app/javascript/flavours/glitch/initial_state.js, app/javascript/flavours/glitch/reducers/settings.js, app/serializers/initial_state_serializer.rb
When "Show boosts in public timelines" or "Show replies in public timelines" setting is enabled, this adds a corresponding toggle to the public and local timeline to filter these out.
"Show replies" works the same as in the home column, so it includes self-replies (threads).
I think that should be addressed separately.
Preview:
=> Add toggle for show replies and show boosts in public timelines when enabled

app/javascript/flavours/glitch/features/ui/containers/status_list_container.js
While threads are technically self-replies, I think excluding those as well is rather unexpected for most people.
I think this should be a separate toggle if included at all.
=> Exclude threads from "Show replies" toggle

app/javascript/flavours/glitch/features/home_timeline/components/column_settings.jsx, app/javascript/flavours/glitch/features/ui/containers/status_list_container.js, app/javascript/flavours/glitch/locales/en.json, app/javascript/flavours/glitch/reducers/settings.js
With the exclusion of self-replies from the "Show replies" toggle, I think it makes sense to include a separate one for self-replies.
Preview:
=> Add "Show threads" setting to home timeline

app/javascript/flavours/glitch/styles/components/announcements.scss, app/javascript/flavours/glitch/styles/components/status.scss
Ref #21 
Moves `reactions-bar--empty` to `announcements.scss` for this rule to be applied in all contexts.
=> Fix empty reaction bar displaying in detailed status view

app/controllers/settings/preferences_controller.rb, app/javascript/flavours/glitch/actions/compose.js, app/javascript/flavours/glitch/features/ui/components/alt_text_warning_modal.jsx, app/javascript/flavours/glitch/features/ui/components/modal_root.jsx, app/javascript/flavours/glitch/features/ui/util/async-components.js, app/javascript/flavours/glitch/reducers/compose.js, app/javascript/flavours/glitch/styles/components/modal.scss, app/javascript/flavours/glitch/styles/fairy-floss/diff.scss, app/javascript/flavours/glitch/styles/mastodon-light/diff.scss, app/javascript/flavours/glitch/styles/oatstodon/diff.scss, app/javascript/mastodon/actions/compose.js, app/javascript/mastodon/features/ui/components/alt_text_warning_modal.jsx, app/javascript/mastodon/features/ui/components/modal_root.jsx, app/javascript/mastodon/features/ui/util/async-components.js, app/javascript/mastodon/locales/en.json, app/javascript/mastodon/reducers/compose.js, app/javascript/styles/mastodon-light/diff.scss, app/javascript/styles/mastodon/components.scss, app/lib/user_settings_decorator.rb, app/models/user.rb, app/serializers/initial_state_serializer.rb, app/serializers/rest/preferences_serializer.rb, app/views/settings/preferences/other/show.html.haml, config/locales-glitch/simple_form.en.yml, config/settings.yml, spec/lib/user_settings_decorator_spec.rb
Port of mastodon/#21679
Changes:
- Moved locales to glitch
- Changed file extension of `alt_text_warning_modal.js` to `.jsx`
- Changed buttons from "Go back" to "Back" and "Publish anyway" to "Publish"
Removed the replaced strings.
- Removed rubocop disable comments in `user_settings_decorator.rb`
- a67ee0310efb5e2518d3760276206f0714fa04bc
=> Add a reminder when publishing new toots with media that has no image description

app/javascript/flavours/glitch/features/account_timeline/components/header.jsx, app/javascript/flavours/glitch/features/featured/index.jsx, app/javascript/flavours/glitch/features/ui/index.jsx, app/javascript/flavours/glitch/features/ui/util/async-components.js, app/javascript/flavours/glitch/locales/defaultMessages.json, app/javascript/flavours/glitch/locales/en.json, config/routes.rb, spec/routing/accounts_routing_spec.rb
Adding featured tags back to profiles.
Originally it was intended to also show featured accounts, but those don't federate and are only visible to yourself, so it's useless.
Preview:
=> Add featured tags to profiles

app/javascript/flavours/glitch/features/getting_started/components/announcements.jsx
Instead of showing the first available announcement, show the first unread announcement by default.
=> Show first unread announcement by default

app/controllers/api/v1/lists_controller.rb, app/javascript/flavours/glitch/actions/lists.js, app/javascript/flavours/glitch/features/list_timeline/index.jsx, app/javascript/flavours/glitch/reducers/list_editor.js, app/javascript/mastodon/actions/lists.js, app/javascript/mastodon/features/list_timeline/index.jsx, app/javascript/mastodon/reducers/list_editor.js, app/lib/feed_manager.rb, app/models/list.rb, app/serializers/rest/list_serializer.rb, db/migrate/20230505093749_polyam_add_exclusive_to_lists.rb, db/migrate/20230505094629_polyam_move_is_exclusive_lists.rb, db/migrate/20230505100107_polyam_remove_is_exclusive_list.rb, db/schema.rb, spec/lib/feed_manager_spec.rb
Should've changed it from the start :/
strong_migrations prevents the use of rename_column, so a new column is created, values of the old column copied and then the old column gets removed.
=> Rename `is_exclusive` to `exclusive`

app/services/notify_service.rb
Ref #21
When trying to send an e-mail, the service fails with a KeyError as e-mail notifications for reactions are not yet supported.
=> Add `reaction` to `NON_EMAIL_TYPES`

app/validators/status_reaction_validator.rb
Ref #21
This is essentially only needed for the fabricator to work, since right now the validator invalidates a reaction which is already existing.
=> Don't invalidate already existing reactions

spec/controllers/api/v1/statuses/reactions_controller_spec.rb, spec/fabricators/status_reaction_fabricator.rb, spec/lib/activitypub/activity/emoji_react_spec.rb, spec/lib/activitypub/activity/undo_spec.rb, spec/models/concerns/account_interactions_spec.rb, spec/models/notification_spec.rb, spec/models/status_reaction_spec.rb, spec/policies/status_policy_spec.rb, spec/services/react_service_spec.rb, spec/services/unreact_service_spec.rb, spec/validators/status_reaction_validator_spec.rb, spec/workers/unreact_worker_spec.rb
I remember starting this a while ago, but I couldn't find the changes in any branch or stash, so in order to not loose progress on this again, this WIP exists.
TODO:
- Make sure all necessary test cases are covered
Done:
- `spec/controllers/api/v1/statuses/reactions_controller_spec.rb`
- `spec/lib/activitypub/activity/undo_spec.rb`
- `spec/models/concerns/account_interactions_spec.rb`
- `spec/model/notification_spec.rb`
- `spec/policies/status_policy_spec.rb`
- `spec/validators/status_reaction_validator_spec.rb`
- `spec/workers/unreact_worker_spec.rb`
- `spec/services/react_service_spec.rb`
- `spec/lib/activitypub/activity/emoji_react.rb`
- `spec/services/unreact_service_spec.rb`
- `spec/models/status_reaction_spec.rb`
=> Add tests for emoji reactions

app/validators/status_reaction_validator.rb
Ref #21
When an account reacts with different custom emojis with the same name, it didn't count as a new reaction and therefore the limit wasn't enforced.
=> Fix being able to bypass `MAX_REACTIONS`

app/models/list.rb, db/migrate/20221125104951_add_is_exclusive_to_list.rb, db/migrate/20230505093749_polyam_add_exclusive_to_lists.rb, db/migrate/20230517195218_polyam_set_exclusive_not_null.rb, db/migrate/20230517195554_polyam_validate_exclusive_not_null.rb, db/schema.rb
Follow-up to #115
I knew I should've set `null: false`, but I didn't because ???
Changing old and already run migrations doesn't make sense, so Rails/ThreeStateBooleanColumn was disabled in old migrations.
=> Fix missing not null for exclusive in lists

app/controllers/api/v2/search_controller.rb, spec/controllers/api/v2/search_controller_spec.rb
While it wasn't possible to use search via the webUI when search was disabled, it was still possible to use the rest API to perform searches.
=> Require auth when search is disabled

.env.production.sample, app/models/invite.rb, app/policies/invite_policy.rb, app/validators/invite_validator.rb, config/locales-glitch/en.yml, spec/controllers/invites_controller_spec.rb, spec/policies/invite_policy_spec.rb, spec/validators/invite_validator_spec.rb
Limit maximum number of active invites to 5.
Limit creation of invites to 20 in the past 24h.
Require accounts to be at least 7 days old to create invites.
These limits can be bypassed by giving the `bypass_invite_limits` permission.
Note:
- 73ef5d4f7b3098de7a3db9027c003b8d9a439cc5 and 4b420de805f8f1a774f598e75e88d570b8850a98 are temporary patches.
=> Add further restrictions on user created invites

app/javascript/flavours/glitch/features/compose/components/emoji_picker_dropdown.jsx
Ref #21
Adds the `flip` prop to `<Overlay>`.
This doesn't fully solve the issue of the emoji picker opening out of screen bounds, but clicking the react button again is such a case opens it correctly.
=> Keep emoji picker within screen bounds

app/javascript/flavours/glitch/actions/compose.js, app/javascript/flavours/glitch/containers/status_container.js, app/javascript/flavours/glitch/features/account_gallery/index.jsx, app/javascript/flavours/glitch/features/status/index.jsx, app/javascript/flavours/glitch/features/ui/components/alt_text_warning_modal.jsx, app/javascript/mastodon/actions/compose.js, app/javascript/mastodon/features/ui/components/alt_text_warning_modal.jsx
Missed that upstream changed how modals are handled.
=> Fix crash when opening alt-text and alt-text-warning modal

app/controllers/admin/custom_emojis_controller.rb, app/views/admin/custom_emojis/new.html.haml, config/locales-glitch/en.yml
Add ability to assign a category.
Add checkbox for showing emoji in emoji picker.
Add new translation strings.
Preview:
Some thoughts:
The checkbox looks a bit off without a hint, but the setting is pretty self-explanatory.
I'm not sure I'm happy with the order of the elements, but I think it's good enough.
=> Update custom emoji upload form

app/controllers/admin/domain_blocks_controller.rb, spec/controllers/admin/domain_blocks_controller_spec.rb, spec/features/admin/domain_blocks_spec.rb
This is currently broken and prevents domain blocks from being upgraded.
This could be fixed by using the correct url for editing blocks, but I decided against it as
this screen also introduces a needless extra click when suspending a domain.
=> Disable confirmation screen when suspending domain

app/controllers/admin/domain_blocks_controller.rb
Clicking the url in the message leads to a 404 as it used the wrong path.
Remaining issue:
I need to dig deeper, but I'm sure this is supposed to prevent a domain block from being created when one with a higher severity already exist, hence the warning message.
But it still creates the block.
=> Fix `unblock_url` leading to 404 when domain block exists

app/javascript/flavours/glitch/components/column.jsx
The unusual way the firehose column is wrapped causes querySelector to get the wrong scrollable element which prevents scrolling to top in the advanced UI.
Instead of having to rewrite the firehose column, this change will select the correct element for scrolling.
=> Fix scrolling to top in firehose column

app/helpers/admin/action_logs_helper.rb
Ref #2 
The link in audit logs always linked to a non-existent path. Instead, link to the edit page for that filter.
This will still lead to a 404 when the registration filter was deleted, but that's in line with other logs.
=> Fix audit logs for registration filters linking to invalid path

app/helpers/admin/action_logs_helper.rb
Alternative to #170
Linking to domains can leak information to potential malicious domains when clicked.
=> Do not link to remote domains in audit log for blocks

app/javascript/flavours/glitch/features/status/components/detailed_status.jsx, app/javascript/flavours/glitch/features/video/index.jsx
When opening the video modal (by clicking "Expand"), the playback is supposed to continue at the current volume.
This behaviour has been broken for a while, because a `lang` prop was passed to the handlers which only expected `options`. There is no point in passing `lang` as it is set later and the modal doesn't do anything with it.
A nice to have adjacent to this would be to pass the current time and volume back to the attachment when closing the modal, but passing props back to components is currently not supported afaik.
=> Fix playback not continuing when opening media modal

app/javascript/flavours/glitch/features/status/index.jsx
Sometimes when clicking replies the replied to toot isn't available yet and because it doesn't dynamically reload, a page reload is required to load more context.
New replies also don't dynamically load in.
I don't know if it ever dynamically loaded or a regression broke it, but this is the easiest workaround.
Instead of having to reload the page, the reload button can be clicked, similar to favourites and boost lists.
It doesn't immediately work for logged out users, probably because of caching/limiting.
=> Add refresh button to detailed status view

app/javascript/flavours/glitch/features/public_timeline/index.jsx
When  `onlyRemote` or `allowLocalOnly` is enabled the federated timeline didn't indicate new toots are available, because `hasUnread` was always false.
=> Fix public TL not indicating new toots when `onlyRemote` or `allowLocalOnly` is enabled

app/javascript/flavours/glitch/styles/components/media.scss
Ref #34 
The alt button is visible on the sensitive media overlay, but not clickable because of the z-index.
This changes the z-index so the button is clickable and opens the alt-text-modal.
Might be a good idea to revert the styling of the badges back to before and change the opacity on hover, so it's more clear it's clickable.
=> Make alt button clickable on sensitive media

db/post_migrate/20230823141504_polyam_remove_index_status_reactions_on_account_id.rb, db/schema.rb
Ref #21 
`index_status_reactions_on_account_id` is covered by `index_status_reactions_on_account_id_and_status_id`
=> Remove duplicate index on status reactions

app/views/settings/featured_tags/index.html.haml
When adding a featured hashtag from a suggestion, it uses the tag name which is always all lowercase instead of the display name, which depends on the first use or is set by admins.
This makes the suggestions less useful as in order to show the tag with the proper name it has to be removed and manually added with proper casing.
=> Use display name when adding featured tag from suggestion

app/models/user_settings.rb
Another change I expected to be merged upstream.
Since the refactor of user settings, this setting had no effect, so instead of removing it, make it apply again.
=> Set `default_content_type` default from `settings.yml`

.env.production.sample, app/models/user_role.rb, app/policies/invite_policy.rb, app/validators/invite_validator.rb, db/post_migrate/20230519010427_polyam_add_invite_limit_bypass.rb, db/post_migrate/20230522123100_polyam_change_bypass_invite_permission_value.rb, spec/validators/invite_validator_spec.rb
Ref #137 
Split-off from #197 
New env var:
- `MIN_DAYS_BEFORE_INVITE` - Amount of days an account has to exist before being able to create invites.
Fixes old migrations from failing when permissions are removed.
Removes using UTC in specs as local timezone is used.
=> Invite restriction improvements

app/javascript/flavours/glitch/actions/interactions.js, app/javascript/flavours/glitch/features/reactions/index.jsx, app/javascript/flavours/glitch/reducers/user_lists.js
Ref #21 
Same as 871ab8485434d9c89dddb14a2ee1fda8ad60035e and beb5fcd0dc158218fd3c82e7d545a53f7dc904b7 as I think reactions are also affected by it.
This also adds follow/unfollow buttons to every account in the list.
=> Fix reacted list only showing latest reacting accounts

app/views/admin/statuses/show.html.haml, config/locales-glitch/en.yml
Ref #21
When clicking "open this toot in the moderation interface" the reaction count was missing from the stats.
=> Add reactions count to toot moderation interface

app/javascript/flavours/glitch/styles/components/status.scss
Vanilla added a different color for private mentions, but the gradient wasn't updated.
=> Fix wrong gradient for collapsed private mentions

app/javascript/flavours/glitch/styles/oatstodon/diff.scss
Ref #76
Oatstodon uses a different background color for private mentions as the mixed colors look bad.
This also uses the background color for the gradient so it doesn't break should the color change upstream
=> [Oatstodon] Match gradient for collapsed private mentions with background

app/javascript/flavours/glitch/styles/components/announcements.scss, app/javascript/flavours/glitch/styles/components/status.scss
Ref #21 
Follow-up to #93 
Adding `.reactions-bar--empty` to `announcements.scss` unfortunately causes the reaction bar to be hidden in announcements, which prevents users from adding reactions.
This actually fixes the issue #93 was supposed to fix.
=> Fix reaction bar being hidden in announcements

app/javascript/flavours/glitch/styles/components/media.scss
Fixes #230 
Partially reverts #201 
This will unfortunately remove the ability to read alt-text before clicking the click to show button.
Preview:
A remaining issue is that unlike in vanilla, the badges are blurred behind the button.
I don't think that's intentional though, as vanilla broke the backdrop filter in `.spoiler-button__overlay__label`, preventing the blur.
=> Don't render alt button above sensitive overlay

app/models/public_feed.rb, spec/models/public_feed_spec.rb
Fixes #207
This might be rather expensive and could be optimised, but I badly need this and I'm happy it works at all.
=> Hide toots interacted by muted, blocked or silenced accounts from public timelines

app/javascript/flavours/glitch/components/status_content.jsx
Ref #20
I didn't have a translation backend configured, so I was reluctant to make this change, but now I do.
Keeps syntax highlighting in translations.
=> Keep Syntax Highlight in translations

app/lib/search_query_transformer.rb
Fixes #220 
Instead of searching public and private indexes by default, only search in private index (old search behaviour), unless `in:all` is specified.
=> Search in private index by default

app/javascript/flavours/glitch/styles/homogay/diff.scss
When loading the advanced UI, the mascot in the left bottom corner had the wrong background color.
=> [Homogay] Fix wrong background for elefriend

app/javascript/flavours/glitch/reducers/compose.js
Follow-up to #255
`action.raw_text` is undefined and needs to be `action.text`
=> Fix editing stripping Markdown

app/javascript/flavours/glitch/features/compose/components/search.jsx
This is a weird one.
When using the same search term and pressing enter and then click "Profiles matching $searchTerm", it appears in recent twice. This itself is not an issue as these are different searches. But trying to dismiss one of these, should remove both and not only one. This results in an undeletable recent search entry as both have been removed in the state, but the UI didn't reflect that. The underlying cause was that the key attribute of the button element was not unique.
=> Fix possible duplicate keys in recent search

app/javascript/flavours/glitch/components/permalink.jsx
Prevents router props being added to links created by Permalink.
=> Fix router props being added to permalinks

app/javascript/flavours/glitch/components/dropdown_menu.jsx, app/javascript/flavours/glitch/components/intersection_observer_article.jsx, app/javascript/flavours/glitch/components/status_content.jsx, app/javascript/flavours/glitch/features/compose/components/navigation_bar.jsx, app/javascript/flavours/glitch/styles/basics.scss, app/javascript/flavours/glitch/styles/components/columns.scss, app/javascript/flavours/glitch/styles/components/compose_form.scss, app/javascript/flavours/glitch/styles/components/drawer.scss, app/javascript/flavours/glitch/styles/components/emoji.scss, app/javascript/flavours/glitch/styles/components/misc.scss, app/javascript/flavours/glitch/styles/components/status.scss, app/javascript/flavours/glitch/styles/variables.scss
Thinking about doing extra changes to make this more consistent, but CSS really isn't my thing and a pain to maintain.
~Oh right, this causes a funny bug with collapsed toots with media~
That bug is already there. It just wasn't that much of an issue because keyboard navigation wasn't viable before.
Passing `isCollapsed` to Poll and AttachmentList and setting tabindex to -1 if true would fix it, but I'm looking for more options and it wouldn't work for mention links as these are created in the backend afaik.
- 0098ee7f6f59d336c8d285ac38446a5690519d5e
- 59ec5cb19b250054d7a3beb90df12fab9ea326ce
=> Port UI focus changes

app/javascript/flavours/glitch/components/attachment_list.jsx, app/javascript/flavours/glitch/components/poll.jsx, app/javascript/flavours/glitch/components/status.jsx, app/javascript/flavours/glitch/components/status_content.jsx
There is a fun bug when using keyboard navigation on collapsed toots, where the visible text will scroll to a focusable element, like the refresh button on polls.
This passes `isCollapsed` to the affected elements to set tabIndex to -1
~This unfortunately doesn't work for mentions and links in the content itself.~
=> Fix collapsed toot scrolling on focus

app/javascript/flavours/glitch/actions/compose.js, app/javascript/flavours/glitch/actions/compose_typed.ts, app/javascript/flavours/glitch/features/compose/components/compose_form.jsx, app/javascript/flavours/glitch/features/compose/containers/compose_form_container.js, app/javascript/flavours/glitch/reducers/compose.js
Fixes #277 
This prevents the compose form from being highlighted outside from onboarding. I'm not sure why it wasn't done this way in the first place.
Okay, I guess this is additional handholding for new users. It just really is distracting for experienced users.
Adds highlighted to state and adds a dispatch to remove highlighting.
~Thinking about this, I probably want to do that properly in typescript.~
Done.
=> Fix compose form being highlighted when replying

app/views/custom_css/show.css.erb
These were removed upstream, effectively disabling role colors.
I'm also experimenting with adding a preview of badges to role settings.
=> Re-add role badge CSS values

app/javascript/flavours/glitch/packs/public.jsx, app/javascript/flavours/glitch/styles/admin.scss, app/views/admin/roles/_form.html.haml
It's very hard to gauge from the settings page whether a custom color works in a given theme or not.
This adds a preview, which shows the badge in the default, light and current selected theme, if different.
This should work as long as the selected custom theme does not change classic colors in variables.
Preview:
=> Add preview for role badge colors

app/javascript/flavours/glitch/features/status/components/detailed_status.jsx
`this.context.router` doesn't exist anymore.
=> Fix wrong link in detailed status for reactions list

app/javascript/flavours/glitch/styles/admin.scss, app/views/admin/roles/_form.html.haml
FIxes #285 
New problem is: The CSS vars don't update immediately, which is why I used inline styles.
Another solution (more of a workaround) could be to only show the preview once a new color is selected.
That wouldn't be ideal though.
Also the color of the role doesn't update on the roles page too, so that's kinda expected, I guess.
=> Fix CSP error in role badge preview

app/models/status_reaction.rb
This prevents status reactions somehow being attached to a reblog instead of the reblogged status.
That scenario is not possible via the webUI but who knows.
=> Ensure status reactions always refer to original status

app/javascript/flavours/glitch/components/badge.jsx, app/javascript/flavours/glitch/features/account/components/header.jsx, app/javascript/flavours/glitch/styles/accounts.scss, app/javascript/flavours/glitch/styles/components/accounts.scss
I can't decide whether to remove the old badge, or keeping it and removing the new badge.
Preview:
- 246dfb3c57700dab26f29a9e49e164f465f7941f
- 00ed7f38acf5e81e2c550dc2a902fb60bdacb67c
- c5935ed5fa346931645bfe602ebfe2dbf6e9d59d
- 8e70d6a63bafd125acd472eeec9905f2bddc28ed (I'm unsure whether to keep it at all, it's kinda useless now :/)
- da549865b6605dfe044eb34682bad403317170ea
=> Port role badge redesign

app/javascript/flavours/glitch/styles/fairy-floss/diff.scss
Fixes the underline being green while the text is orange.
Doesn't fix the color of the text.
Should be considered a quick, dirty fix.
I intend to refactor this skin.
=> FairyFloss: Fix wrong underline color in link previews

app/javascript/flavours/glitch/styles/admin.scss, app/views/admin/roles/_form.html.haml
Many custom themes override `account__header__bar` instead or in addition of modifying `ui-base-color`.
Makes the preview more robust by using the same CSS class.
=> Change preview for custom theme

app/javascript/flavours/glitch/styles/oatstodon/diff.scss, app/javascript/flavours/glitch/styles/oatstodon/variables.scss
This one will be considerably less work as it is mostly solid.
Same goal as with FairyFloss: Have less diff, make this easier to maintain and less fragile.
Changes:
- Background colors in local settings have been switched.
- CW button color is now more readable
- All links in toots are now accent-colored
- Account section headline and notification filter bar have been simplified
- The same element can now have bottom and top corners in column-link.
- `darker-text-color` reverted to default (It was the same as `dark-text-color`)
- Color overrides for private mentions removed (It actually works as is and was introduced as upstream had no special backgrounds)
- Applied correct border to back buttons
- Changed button background to be darker (dark text doesn't look good)
- Changed color of …
=> Refactor Oatstodon theme

app/javascript/flavours/glitch/styles/oatstodon/diff.scss
Follow-up to #296 
Forgot to test this.
Changes the background to a dark one and hover background to match.
=> Fix autosuggest colors in Oatstodon theme

app/controllers/api/v1/accounts/pins_controller.rb, app/javascript/flavours/glitch/actions/accounts.js, app/javascript/flavours/glitch/features/account_timeline/components/header.jsx, app/javascript/flavours/glitch/features/featured/index.jsx, app/javascript/flavours/glitch/features/pinned_accounts_editor/containers/account_container.js, app/javascript/flavours/glitch/features/pinned_accounts_editor/index.jsx, app/javascript/flavours/glitch/features/ui/index.jsx, app/javascript/flavours/glitch/reducers/pinned_accounts_editor.js, app/javascript/flavours/glitch/reducers/user_lists.js, app/javascript/flavours/polyam/locales/en.json, config/routes.rb, config/routes/api.rb, spec/controllers/api/v1/accounts/pins_controller_spec.rb, spec/routing/accounts_routing_spec.rb
Fixes #204 
Adds `api/v1/accounts/{id}/pinned` endpoint returning the endorsed accounts of `{id}`
Kept `api/v1/endorsements` endpoint just in case apps use these.
TODO:
=> Add endorsed accounts to profiles

app/lib/themes.rb, app/views/shared/_web_app.html.haml, config/webpack/configuration.js, spec/controllers/application_controller_spec.rb
Somewhat related to #306 
This change keeps the files, but disables the vanilla flavour and also skips precompiling vanilla files.
Keeping files is necessary as otherwise git gets confused and tries to apply changes to wrong files on upstream merges.
=> Disable vanilla flavour by default

app/javascript/flavours/glitch/theme.yml, app/javascript/flavours/vanilla/theme.yml, app/views/shared/_web_app.html.haml
Follow-up to #307
This preload is actually already handled by glitch-soc's theming system.
Basically the theming system preloads these and the view preloads them a second time conditionally.
Also this hardcoded paths, which isn't ideal.
=> Remove redundant asset preload

app/views/admin/settings/appearance/show.html.haml
Basically always the default fallback was shown as the label methods were wrong.
After some digging, this has never worked properly before
=> Fix label method for flavour and skin in server settings

app/javascript/flavours/glitch/features/video/index.jsx, app/javascript/flavours/polyam/features/video/index.jsx
Fixes #308 
Hides the alt button when a video attachment is opened in the media modal.
Showing the alt button in the modal doesn't make sense and also `onOpenAltText` is undefined in that case.
=> Don't show alt button in media modal

app/javascript/flavours/polyam/actions/notifications.js, app/javascript/flavours/polyam/actions/notifications_typed.ts
Follow-up to #319 
The first one seems to be on me, the second was an upstream issue.
This fixes custom notification sounds not playing.
=> Fix typo in `notificationsUpdate` call and setting wrong meta

app/javascript/flavours/polyam/features/account/components/account_note.jsx
Seems like the component didn't exist when account notes were added.
Instead of mocking icon buttons, use icon butten.
This also caused a prop error, since Icon doesn't accept size property.
No functional change.
=> Use IconButton component in account notes

app/javascript/flavours/polyam/features/account/components/account_note.tsx
Follow-up to #332 
I think this will also be the direction upstream is going, so remove instead of restore in IconButton
=> Remove size property in account note

app/javascript/flavours/polyam/features/audio/index.jsx, app/javascript/flavours/polyam/features/video/index.jsx, app/javascript/flavours/polyam/reducers/media_attachments.js
This reverts commit 885fd9b7ef6984d726724d55265557997d0e9d92.
This prevented volume change from working on audio attachments.
I could probably fix that or wait for upstream to fix, but not worth it for a change I was reluctant to port anyway.
This might be added back once the issue is fixed upstream.
=> Revert "[Polyam] Feature - Prevents multiple audio/video attachments from being played at the same time"

app/lib/settings/scoped_settings.rb, app/models/form/admin_settings.rb, app/views/admin/settings/other/show.html.haml, config/locales-glitch/de.yml, config/locales-polyam/en.yml
Partially reverts #9 
I thought I already removed it. Oops.
When I implemented this, I thought upstream forgot about this setting.
I have since seen some people argue it should be up to users to decide whether they show their application and I agree.
=> Remove admin override for show application

Gemfile.lock
aka fix polyam-glitch being uninstallable because of yanked gem
Thought this was already included in latest vanilla merge :/
Conflicts:
- `Gemfile.lock`
Upstream updated a dependency, but others were ahead.
Updated dependencies upstream did
- b6ee987ea799b4da4e955a04b900492e6c1c4817
=> Merge upstream changes

app/lib/themes.rb, config/webpack/configuration.js
Fixes #340 
This, like `ENABLE_VANILLA` and `RAILS_ENV` is used before loading `.env` file
Though it can be used in an env file, it would still compile assets of disabled skins needlessly.
Default skin cannot be disabled as it is used as a fallback.
Example:
`DISABLED_SKINS="oatstodon,fairy-floss"`
=> Add env var to disable skins

app/views/settings/preferences/appearance/show.html.haml, config/locales-polyam/simple_form.en.yml
Fixes #338 
This has been misleading as these settings also apply to the polyam flavour.
I don't really have the confidence this would be changed upstream right now :/
Thinking about adding another string with the parentheses content, which is shown conditionally when the vanilla flavour is enabled, but this would likely just push the issue downstream should someone decide to fork this project.
=> Replace locale strings containing "applies to Glitch flavour only"

app/lib/themes.rb
When adding a directory in one of the skins directories, it is immediately selectable as a skin even when there are no files.
When creating a theme at least one (S)CSS is required though.
This skips the skin if there is no file.
=> Fix empty directories count as selectable themes

app/javascript/flavours/polyam/styles/homogay/diff.scss
The refactor of the compose form doesn't hide this element anymore and it had a different color, which made it look like the buttons area was bigger than it is.
Before:
After:
=> Fix background color of modifier wrapper

app/models/domain_block.rb, app/views/admin/export_domain_blocks/_domain_block.html.haml, app/views/admin/instances/show.html.haml, config/locales-polyam/en.yml
`noop` is filtered from policies, so instead of showing policies in the admin interface it is non-existent for domain blocks with the "None" severity.
This displays "None" instead
=> Fix policy display for domain blocks with none severity

app/javascript/flavours/polyam/styles/homogay/diff.scss
It was "light themed" which doesn't work.
=> Fix spoiler button background in report modal in homogay

app/javascript/flavours/polyam/initial_state.js
It's an object of numbers, not a number.
=> Fix type annotation for `poll_limits` in initial state

app/javascript/flavours/polyam/styles/homogay/diff.scss
Follow-up to #363 
The background color of the element was wrong in simple UI instead of advanced UI.
This fixes the wrong color for both.
=> Fix background color of modifier wrapper (again)

app/javascript/flavours/polyam/styles/components/status.scss
Fixes alignment of media icons in CW button by adding `align-items` attribute.
=> Fix media icons in CWs

app/javascript/flavours/polyam/components/status_action_bar.jsx, app/javascript/flavours/polyam/features/account/components/header.jsx, app/javascript/flavours/polyam/features/status/components/action_bar.jsx
Removes the red text from menu entries
There are several problems with marking certain menu entries with red text.
It gives the impression these are disabled or "forbidden" and makes people reluctant to take actions.
The contrast is also not great.
=> Remove `dangerous` from menu entries

app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/diff.scss
Sets the background to transparent, like default.
Not the best design, but better than current.
Before:
After:
=> Fix background of disabled vote button in polls in homogay theme

app/javascript/flavours/polyam/styles/components/misc.scss
Match size with upstream while not making icon comically large.
The icon itself still appears smaller than before the icon change, but that's because the eye was shrunk down.
=> Fix size of media spoiler button

app/services/unreact_service.rb
A non-existent reaction should already be covered by rescuing RecordNotFound.
=> Remove unnecessary return in `UnreactService`

app/controllers/api/v1/statuses/reactions_controller.rb, app/serializers/rest/status_serializer.rb
Applies the count in response fix of 4c18928a931c8dc149fa3e0bd7de8ce4f6242715 to reactions
=> Fix `reactions_count` not being updated on unreact

app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/diff.scss
Due to the CSS refactor those classes no longer applied
=> Fix compose suggestions colors in homogay theme

app/javascript/flavours/glitch/styles/fairy-floss/diff.scss, app/javascript/flavours/polyam/styles/fairy-floss/diff.scss
Fixes white corners in textarea of compose panel by making the background of the wrapper transparent
=> Fix white corners in simple UI textarea in FairyFloss

app/javascript/flavours/glitch/styles/fairy-floss/diff.scss, app/javascript/flavours/polyam/styles/fairy-floss/diff.scss
Background override now needs to be applied directly to header class.
Also account-note textarea focus.
=> Fix background of profiles in FairyFloss

app/javascript/flavours/glitch/features/account_gallery/components/media_item.jsx, app/javascript/flavours/polyam/features/account_gallery/components/media_item.jsx
The class changed from `media-gallery__alt__button` to `media-gallery__alt__label` since upstream implemented an alt label.
=> Fix wrong class being used for alt-button in gallery

app/javascript/flavours/polyam/components/status_action_bar.jsx, app/javascript/flavours/polyam/components/status_prepend.jsx, app/javascript/flavours/polyam/features/compose/components/emoji_picker_dropdown.jsx, app/javascript/flavours/polyam/features/notifications/components/filter_bar.jsx, app/javascript/flavours/polyam/features/reactions/index.jsx, app/javascript/flavours/polyam/features/status/components/action_bar.jsx, app/javascript/flavours/polyam/features/status/components/detailed_status.jsx, app/javascript/flavours/polyam/styles/components/accounts.scss, app/javascript/flavours/polyam/styles/components/status.scss
Follow-up to #440 
Changes the icon for reactions, removes `reactButton`, fixes some styling issues
=> Emoji react fixes for new picker buttons

app/javascript/flavours/polyam/features/account/components/header.jsx, app/javascript/flavours/polyam/styles/components/accounts.scss
Fixes #431 
Profile fields are visually appealing, which results in the text being skipped.
Shows them above bio again as was the case before.
=> Show profile fields above bio again

streaming/index.js
Wasn't added to type definitions.
Doesn't affect functionality.
=> Fix type issue with `allow_local_only` in streaming

app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/diff.scss
This was a leftover from the old compose design.
=> Remove border-radius from spoiler-input

app/javascript/flavours/polyam/styles/components/compose_form.scss
It looks better without these and quite frankly, I think they were a bad idea and discourage usage of CWs.
Before:
After:
=> Remove warning stripes around CW input

app/javascript/flavours/polyam/styles/components/_mixins.scss, app/javascript/flavours/polyam/styles/components/accounts.scss, app/javascript/flavours/polyam/styles/components/columns.scss, app/javascript/flavours/polyam/styles/components/compose_form.scss, app/javascript/flavours/polyam/styles/components/drawer.scss, app/javascript/flavours/polyam/styles/components/index.scss, app/javascript/flavours/polyam/styles/components/notification.scss, app/javascript/flavours/polyam/styles/components/status.scss
Upstream has a nasty habit of overriding its own style. Due to different structure and therefore load order, this sometimes causes overrides to not apply correctly and makes it necessary to put overrides in files where they don't belong or split classes and apply changes to all of them.
This creates a mixin file for component CSS to avoid duplication.
=> Create mixins for component SCSS

app/javascript/flavours/polyam/actions/alerts.js, app/javascript/flavours/polyam/actions/compose.js, app/javascript/flavours/polyam/features/notifications/containers/column_settings_container.js, app/javascript/flavours/polyam/features/ui/containers/notifications_container.js, app/javascript/flavours/polyam/reducers/alerts.js, app/javascript/flavours/polyam/selectors/index.js, app/javascript/flavours/polyam/styles/components/notification.scss
This was skipped, because I find it annoying, but the code changes are not bad.
But the main reason to port this is because of the repeated confusion due to the misleading CSS class names.
So, port but disable.
=> Port published toast

app/javascript/flavours/polyam/styles/components/search.scss
Follow up to #456 
This removal was somehow not displayed in the diff.
Fixes:
=> Fix search icon position

app/views/user_mailer/welcome.html.haml, app/views/user_mailer/welcome.text.erb
Follow-up to #460 
The "official" apps should be considered bootleg and no-one should use them.
I wish upstream would stop shoving them into people's faces.
I would rather replace the recommendation to include Tusky and Megalodon for Android apps, but I'm not sure which ones are currently recommended for iOS
=> Remove apps from new welcome email

app/javascript/flavours/glitch/packs/public.tsx, app/javascript/flavours/polyam/packs/public.tsx
Follow-up to #476 
`querySelector` didn't return any element, so use `getElementById` again instead.
=> Fix delegation for role badge preview

app/views/admin/roles/_form.html.haml
There is currently no point in showing it in glitch flavour as glitch now also doesn't support role badge colors.
=> Also disable role badge preview for glitch flavour

app/javascript/flavours/polyam/styles/components/drawer.scss
The header was slightly smaller than column headers.
This adjustment makes them same sized.
=> Adjust padding for `.drawer_tab`

app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/glitch/styles/homogay/variables.scss, app/javascript/flavours/polyam/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/variables.scss
The new modals have a border-radius which conflicted with the background set in `.modal-root__modal`
=> Fix background of new modals in homogay

app/views/settings/preferences/notifications/show.html.haml, app/views/settings/preferences/other/show.html.haml, config/locales-polyam/en.yml
Notification setting has been renamed to e-mail notifications and other settings have been removed in favour of notification requests, so it makes more sense there.
=> Move notification sound setting to "Other"

app/javascript/flavours/polyam/styles/admin.scss
Caused by adding margin to the component version and it's reused in moderation interface.
Before:
After:
=> Fix misaligned account bio in moderation interface

app/javascript/flavours/polyam/styles/admin.scss
Follow-up to #495 
The elements display as horizontal instead of vertical columns without it.
Preview:
=> Add removed `nowrap` to account moderation interface

app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/diff.scss
Removing transparency is no longer needed as upstream fixed the background.
Overriding borders is no longer necessary as upstream removed them.
Added background override for category label as transparent label looks wrong.
=> Fix overrides for emoji picker in homogay

.env.production.sample, app/models/trends/statuses.rb
Adds a new env var: `TRENDS_TOOT_HALFLIFE`
4 is just a random number that seems to make sense.
=> Increase score half-life for trending toots

app/helpers/application_helper.rb, app/javascript/flavours/glitch/styles/forms.scss, app/javascript/flavours/polyam/styles/forms.scss, app/javascript/styles/mastodon/forms.scss, app/models/form/admin_settings.rb, app/models/site_upload.rb, app/presenters/instance_presenter.rb, app/serializers/initial_state_serializer.rb, app/views/admin/settings/branding/show.html.haml, app/views/layouts/application.html.haml, config/locales/simple_form.en.yml
Closes #206
Closes #241
Ref #7 
This setting has been semi-broken for a while and I don't feel confident in fixing this without making major changes.
If there is enough interest I might look back into it, but for now it's not really worth fixing.
Using the `branding:generate_app_icons` task instead is recommended.
Just replace `app/javascript/images/logo.svg` and `app/javascript/images/app-icon.svg` with the svg of the icon you want to use and then run `RAILS_ENV=production bundle exec rake branding:generate_app_icons` \
(Or better in a local dev environment and commit the result to your repo to avoid issues when pulling updates)
=> Remove server favicon setting

app/javascript/flavours/glitch/styles/fairy-floss.scss, app/javascript/flavours/glitch/styles/fairy-floss/diff.scss, app/javascript/flavours/glitch/styles/fairy-floss/variables.scss, app/javascript/flavours/polyam/styles/fairy-floss.scss, app/javascript/flavours/polyam/styles/fairy-floss/diff.scss, app/javascript/flavours/polyam/styles/fairy-floss/variables.scss
This greatly reduces the diff and should make maintaining it less painful
Not sure `mint` as boost icon color still makes sense, but I kept it, because it was there before.
Changed background to a darker variant to make it easier on the eyes.
Adjusted reaction-bar colors for new background.
Simplified modal background overrides.
Color hashtags in hashtag bar same as in toots.
Before:
After:
=> Update FairyFloss to new monocolor design

app/javascript/flavours/polyam/styles/tables.scss
This prevents the icon and text from wrapping when part of element with long text. Specifically the rule page when the rule text or upcoming hint is very long.
This is probably the first `nowrap` that has an actual good reason to be there.
Before:
After:
=> Add `nowrap` to table-action-link

app/javascript/flavours/polyam/features/getting_started/index.jsx
Upstream changed type from map to record a while ago. This got never updated apparently.
=> Fix propType of myAccount in getting_started

app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/diff.scss
Upstream uses a darkened background, so using the base color makes the background the same.
=> Fix hashtag bar background in homogay

app/controllers/api/v2/filters_controller.rb, app/models/custom_filter.rb, app/serializers/rest/filter_serializer.rb, spec/requests/api/v2/filters_spec.rb
Follow-up to #228 
Add a constant for the instance filter id and use instead actor id constant to create the filter.
This has the benefit of not having to look up the id unnecessarily in the db.
Also uses the new constant in some places as the filter doesn't need to exist in them.
Fixes system specs.
=> Use constant for instance filter instead of magic number

app/helpers/application_helper.rb, app/javascript/flavours/polyam/styles/admin.scss, app/views/admin/custom_emojis/index.html.haml, app/views/admin/reports/_status.html.haml, app/views/admin/status_edits/_status_edit.html.haml, config/initializers/propshaft.rb
Lets `material_symbol` return an awesome icon instead of material.
Add helper to replace material names with awesome names.
Adds propshaft config to load Font Awesome icons.
Adds `variant` to some icons
=> Add FontAwesome icons to admin/settings views

app/javascript/flavours/polyam/styles/mastodon-light/variables.scss
Glitch-soc's themeing system uses `skin-` instead of `theme-` so the overrides in the light theme didn't apply.
=> Fix classname for light theme in variables

app/helpers/application_helper.rb
Follow-up to #521 
Some material icon files have `-fill` in their name, which is pointless for font awesome as it is equivalent to "solid".
The `-` was missing which would result in icons like `bell-` being returned.
=> Add missing `-` to chomp in `material_to_awesome`

app/helpers/application_helper.rb
Follow-up to #521
Some icons were missed.
Also some icons use the same name, but are an alias not actual file name for FA.
=> Add missing Font Awesome replacements to `material_to_awesome`

app/javascript/flavours/polyam/api_types/statuses.ts
Instead of `string` type it with actual values.
=> Type `content_type` more accurately

app/lib/themes.rb, config/webpack/configuration.js
Follow-up to #345 
The new system theme requires the default and mastodon-light skin so explicitly delete them from `DISABLED_SKINS` if set.
=> Explicitly ignore disabling of required skins

.eslintrc.js
Add additional rule to no-restricted-paths to disallow imports from material-icons
=> Forbid import of Material icons in polyam flavour

app/javascript/flavours/polyam/names.yml
Not sure why upstream didn't do this, but I guess how locales for themes are handled is about to change.
=> Add name for system theme

app/javascript/flavours/polyam/styles/components/accounts.scss
Fixes #502 
Before:
After:
TODO:
=> Change design of icon buttons in account relationships

app/views/layouts/application.html.haml
This should've been overridden in an upstream merge, but wasn't.
Fixes giving `theme_color_tags` unexpected values, so color tags are set correctly for system skin.
=> Use `current_theme` for `theme_color_tags`

app/controllers/concerns/theming_concern.rb, app/controllers/settings/flavours_controller.rb, app/models/concerns/user/has_settings.rb, app/models/user_settings.rb, app/views/settings/flavours/show.html.haml, config/locales-polyam/simple_form.en.yml, spec/controllers/application_controller_spec.rb, spec/controllers/settings/flavours_controller_spec.rb
Allows users to override the admin setting.
Adds new settings to flavour settings.
Settings default to admin setting or default skins if not available in selected flavour.
Preview:
=> Add user setting to customize light/dark skins in system skin

config/environments/test.rb, lib/mastodon/cli/media.rb, spec/lib/mastodon/cli/media_spec.rb, spec/rails_helper.rb
`config/environment/test.rb` already defines `spec/test_files` as root path, but this seems to be overridden by `config/initializers/paperclip.rb`
This caused media uploads from specs being left in `public/system` after ran locally.
=> Fix specs adding media to `public/system`

app/javascript/flavours/glitch/features/ui/components/alttext_modal.jsx, app/javascript/flavours/polyam/features/ui/components/alttext_modal.jsx
Replaces deprecated context type with `withRouter`
=> Use modern router context in alt-text modal

app/javascript/flavours/polyam/actions/accounts.js
Follow-up to #316 
Fixes missed change in f6476d7196165143ee81cbd4eec6ef626f84a607
=> Fix missing param in `followAccountFail`

Gemfile, Gemfile.lock
This gem broke on systems with ICU75 causing an error when running `bundle install`
This uses a temp fork which removed the unused broken code
=> Use temp fork of `charlock_holmes`

app/serializers/rest/account_serializer.rb
The previous check returned true for newly created accounts resulting in the banner showing "it's usernames 0th fediversary".
This adds an additional condition to not show the banner if the current year matches the creation year.
=> Fix showing fediversary banner on registration day

.github/dependabot.yml
Intended to be used to update polyam-glitch dependencies
Might be used to also update glitch-soc only dependencies
Upstream uses renovate, but as only a handful of packages need to be updated for polyam-glitch, dependabot is the better choice.
=> Add dependabot config back

app/lib/admin/metrics/dimension/software_versions_dimension.rb
Follow-up to #588 (4a5442edaa5d598eea969ac023dc394761f38d7b)
`ffmpeg -version` can output versions that differ from a simple number version, which throws a NoMethodError and results in the component not loading.
Instead match any version string that could be returned.
=> Fix ffmpeg version check

app/lib/admin/metrics/dimension/software_versions_dimension.rb
Follow-up to #590
When the version strings are in an unexpected format, the match is nil, which throws an NoMethodError, when trying to access the capture group.
This changes the regex to not rely on a capture group, which results in an empty string instead when nothing is matched.
This isn't ideal either, but far better than the current behavior.
=> Don't rely on capture group in version check regex

app/javascript/flavours/polyam/features/notifications/components/checkbox_with_label.jsx
type "children" doesn't exist and throws an error in dev env
=> Fix PropType of `children` in CheckBoxWithLabel

app/javascript/flavours/polyam/api/notification_policies.ts
Follow-up to #593 (d558dfd77dc4f64d3a633efcfc0683ee603a1520)
`apiRequest` already adds a `/` after "/api", which results in the requests being `/api//v1/notifications/policy`
That still worked somehow, but I'd rather have correct URLs
=> Remove additional `/` from notification policy requests

app/javascript/flavours/polyam/api/notification_policies.ts
This was caused by a now unneeded exception for restricted paths.
=> Fix accidental import from mastodon in notification policy

app/javascript/flavours/glitch/components/status.jsx, app/javascript/flavours/glitch/containers/status_container.js, app/javascript/flavours/glitch/features/account_gallery/index.jsx, app/javascript/flavours/glitch/features/status/components/detailed_status.jsx, app/javascript/flavours/glitch/features/status/index.jsx, app/javascript/flavours/glitch/features/ui/components/alttext_modal.jsx, app/javascript/flavours/glitch/features/ui/components/modal_root.jsx, app/javascript/flavours/glitch/styles/components.scss, app/javascript/flavours/polyam/components/status.jsx, app/javascript/flavours/polyam/containers/status_container.js, app/javascript/flavours/polyam/features/account_gallery/index.jsx, app/javascript/flavours/polyam/features/status/components/detailed_status.jsx, app/javascript/flavours/polyam/features/status/index.jsx, app/javascript/flavours/polyam/features/ui/components/alttext_modal.jsx, app/javascript/flavours/polyam/features/ui/components/modal_root.jsx, app/javascript/flavours/polyam/styles/components/modal.scss
Refactors the alt-text-modal and changes the design to match upstream's new modal design.
Passing `statusId` to the modal served no purpose and it didn't need router props either.
The modal now shows translated image description when toot was translated.
Preview:
=> Change design of alt-text-modal

app/javascript/flavours/polyam/features/status/components/card.jsx, app/javascript/flavours/polyam/styles/components/status.scss
Reorders style attributes, replaced polyam-glitch changed attributes with upstream, removed unneeded override.
This brings the design closer to upstream.
Before:
After:
=> Reduce difference in status cards with upstream

app/javascript/flavours/polyam/styles/components/announcements.scss, app/javascript/flavours/polyam/styles/components/status.scss
Alternative to #630 
The empty bar has to be shown in announcements as otherwise the react button is also hidden. But outside announcements it adds weird spacing and needs to be hidden.
Currently `.reactions-bar--empty` was and needed to be added to every place they were shown outside announcements to hide the empty bar.
This hides the empty reactions bar by default and adds an exception to announcements instead
=> Hide reactions bar by default outside announcements

app/javascript/flavours/polyam/styles/components/notification.scss
I thought upstream would fix this, but they made it clear it's an intentional "design choice".
This removes the margin and width for status elements in ungrouped notifications to waste less space.
Before:
After:
=> Remove margin and restricted width from ungrouped notifications

app/javascript/flavours/polyam/styles/components/status.scss
Follow-up to #624
I added an extra "s" by accident while porting grouped notifications UI.
=> Fix typo in notification-ungrouped classes

app/javascript/flavours/polyam/reducers/notification_groups.ts
Fixes #636 
Skips `shouldMarkNewNotificationsAsRead` by adding a param that will always be false to always mark new notifications as unread.
I see no value in automatically marking notifications as read.
=> Fix new grouped notifications not marked as unread

app/javascript/flavours/polyam/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/variables.scss
Follow-up to #638 
I'm not sure I like the inputs being lighter now.
I preferred them darker, but I'll keep that for now.
Changed the background color to be darker as `--background-color` and `$ui-base-color` are the same.
Thanks to CSS vars, it can be easily overridden.
Kept the different background for the sidebar as the UI looked a bit too boring with a single color.
=> Update homogay to new admin UI design

app/javascript/flavours/polyam/styles/homogay/variables.scss
This is a good balance between just enough contrast and not too bright of a color.
Fixes too low contrast of text from backgrounds.
=> Make dark text color slightly brighter in homogay

app/javascript/flavours/polyam/styles/homogay/variables.scss
Follow-up to #640 
Because the CSS vars now attach to body, the vars for toot backgrounds used the background color var from the default skin.
This just copies the vars as is to fix that.
=> Fix backgrounds of focused toots and private mentions in homogay

app/views/settings/preferences/appearance/show.html.haml
This is a very minor thing, but the input was correctly typed as "number", simple_form however attached string classes.
This explicitly tells simple_form it's an integer input by adding `as: :integer` to apply correct classes.
=> Change visible reactions setting to be numeric

app/javascript/flavours/polyam/components/follow_button.tsx, app/javascript/flavours/polyam/features/account_timeline/containers/header_container.jsx, app/javascript/flavours/polyam/features/directory/components/account_card.tsx, app/javascript/flavours/polyam/features/ui/components/confirmation_modals/unfollow.tsx
Follow-up to #649 
I still think having a different message in the confirmation modal is less confusing.
A follow request is more of a "follow" than a follow.
The requested value needs to be passed down to the modal as trying to retrieve the value from account yields undefined.
=> Keep different message for cancelling follow request

app/models/instance.rb, app/models/instance_filter.rb, app/views/admin/instances/index.html.haml, config/locales-polyam/en.yml, spec/models/instance_spec.rb
Fixes #651 
Adds a new text field and param to allow searching instances by domain block public and private comment
Preview:
=> Add ability to search domains by comment

public/robots.txt
You should redirect those request and poison the data, but I started this, so I continue to add them.
=> Disallow more LLM scrapers in robots.txt

app/controllers/admin/report_notes_controller.rb, app/models/notification.rb, app/models/notification_group.rb, app/models/report_note.rb, app/serializers/rest/notification_group_serializer.rb, app/serializers/rest/notification_serializer.rb, app/serializers/rest/report_note_serializer.rb, app/services/notify_service.rb
Ref #657 
TODO:
- Add specs (admin notifications don't really seem to have specs)
Adds new `admin.report_note` type and optional `report_note` attribute to Notification
```JSON
{
//... See Notification entity in upstream docs
"report_note" : {
"id": "123456",
"content": "This is a test note",
"created_at": "2019-11-23T07:28:34.210Z",
"report": {
"id": "654321",
"action_taken": false,
//... See Report entity in upstream docs
}
}
}
```
=> Add notifications for report notes

app/javascript/flavours/polyam/features/report/rules.jsx
Fixes #656 
Upstream doesn't want to show the hint in the web UI, but I think it's useful as the hint can be used to clarify rules, which avoids having users to visit the about page when unsure which rule to select when reporting.
I also think the redesign of modals will take long enough that it's worth adding now.
Preview:
=> Add rule hint to rule selector in report modal

app/javascript/flavours/polyam/styles/homogay/diff.scss
The checkmark had the same color as the box, which made it invisible.
This changes the color to the ui base color.
Not sure it's the best color, but it has the highest contrast.
=> Fix checkmark color in report modal in homogay

app/views/admin/domain_blocks/_form.html.haml, app/views/admin/instances/show.html.haml
This allows easier adding and editing of private comments by giving more space.
Also when hitting enter on string inputs, it sends the form, with a text input that doesn't happen.
I'm also considering to change the markup of private comments, so the formatting is preserved.
Preview:
=> Convert private comment field on domain blocks to text input

app/lib/activitypub/activity.rb, app/lib/activitypub/activity/emoji_react.rb, app/lib/activitypub/activity/like.rb, app/lib/activitypub/activity/undo.rb
This is cleaner and matches shortcodes which are actually accepted.
The old regex matched everything between two colons, even invalid shortcodes.
=> Reuse CustomEmoji RegEx for reactions

app/lib/status_cache_hydrator.rb, app/models/status.rb, app/serializers/rest/status_serializer.rb, spec/lib/status_cache_hydrator_spec.rb
There is no explanation as to why this is needed or what if any problem it solves, but other interactions are hydrated, so it seems logical to do the same with reactions.
Also added a new test to hydrate specs.
=> Cherry-pick cache hydration from upstream PR

app/javascript/flavours/polyam/reducers/notification_groups.ts
This reverts commit 82da958086dddcad57a4fe0d8e7f5db7356b2634.
=> Revert "Fix new grouped notifications not marked as unread (#637)"

app/helpers/application_helper.rb, app/views/admin/account_warnings/_account_warning.html.haml, app/views/admin/accounts/_remote_account.html.haml, app/views/admin/accounts/index.html.haml, app/views/admin/accounts/show.html.haml, app/views/admin/custom_emojis/index.html.haml, app/views/admin/dashboard/index.html.haml, app/views/admin/email_domain_blocks/index.html.haml, app/views/admin/export_domain_blocks/_domain_block.html.haml, app/views/admin/export_domain_blocks/import.html.haml, app/views/admin/follow_recommendations/show.html.haml, app/views/admin/instances/show.html.haml, app/views/admin/invites/_invite.html.haml, app/views/admin/ip_blocks/index.html.haml, app/views/admin/relationships/index.html.haml, app/views/admin/relays/_relay.html.haml, app/views/admin/reports/_header_card.html.haml, app/views/admin/reports/_status.html.haml, app/views/admin/reports/actions/preview.html.haml, app/views/admin/reports/show.html.haml, app/views/admin/roles/_role.html.haml, app/views/admin/settings/shared/_links.html.haml, app/views/admin/status_edits/_status_edit.html.haml, app/views/admin/statuses/index.html.haml, app/views/admin/tags/show.html.haml, app/views/admin/trends/links/index.html.haml, app/views/admin/trends/links/preview_card_providers/index.html.haml, app/views/admin/trends/statuses/_status.html.haml, app/views/admin/trends/statuses/index.html.haml, app/views/admin/trends/tags/index.html.haml
Removes `material_to_awesome`
Changes `material_symbol` to require a Font Awesome alternative icon.
This approach has the advantage of not needing a huge case-when chain or some icon map to replace icons. And icons can be replaced one-for-one in case upstream uses the same icon for different things while polyam-glitch wants to use different icons. The downside is that this param needs to be added every time this method is used, even when the icon name overlapses.
=> Add `fa_icon` param to `material_symbol`

app/javascript/flavours/polyam/styles/components/status.scss
Add `align-self` property to icon in `.status-prepend`
Not sure what happened here, but there was a difference with upstream.
The fix for only making the icon colored isn't necessary anymore as upstream seems to have removed the coloring. (Or I messed up the port, though I do compare changes to upstream)
=> Fix alignment of icons in status prepend

app/javascript/flavours/polyam/styles/components/notification.scss
Makes the accept and deny buttons larger to match upstream's size.
This essentially increases the clickable area without changing the icon size.
=> Increase button size in follow request notifications

app/javascript/flavours/polyam/components/follow_icon_button.tsx, app/javascript/flavours/polyam/features/notifications_v2/components/notification_follow.tsx, app/javascript/flavours/polyam/features/notifications_v2/components/notification_follow_request.tsx, app/javascript/flavours/polyam/features/notifications_v2/components/notification_group_with_status.tsx, app/javascript/flavours/polyam/styles/components/notification.scss
- 32a78e56e0a9934f65b89a455f2d118642b998de
The gap between the avatar and "x followed you" text is an upstream issue.
The new notification design really doesn't leave much room for customisation, but I don't have any better ideas.
Preview:
=> Port changes adding follow button to follow notifications

app/views/admin/accounts/_local_account.html.haml
Follow-up to #687
`address_card` -> `address-card`
=> Fix typo in icon name

app/helpers/application_helper.rb, app/views/admin/reports/_status.html.haml, app/views/statuses/_detailed_status.html.haml, app/views/statuses/_simple_status.html.haml, config/initializers/propshaft.rb
Fixes some icons not working because they aren't available.
For custom icons, variant needs to be set to empty string as otherwise it defaults to solid FA icons.
The `awesome_icon` method was changed to only add a `/` when variant isn't an empty string.
=> Add custom icons to propshaft config

app/javascript/flavours/polyam/styles/admin.scss, app/javascript/flavours/polyam/styles/tables.scss
Fixes #693
This improves the alignment of icons by changing `vertical-align` to `text-bottom` in `.admin-wrapper` and keeping `top` in `.table-action-link`
A consistent style without having to override would be preferred, but that would require more significant changes.
Before:
After:
=> Fix alignment of icons in views

app/javascript/flavours/polyam/styles/accessibility.scss
Upstream removed FA font, which was used for the checkmarks. This resulted in the checkmarks being broken when FA wasn't installed locally. This changes it to use the FA6 checkmark icon as SVG instead.
Before:
After:
=> Fix checkmarks on status icons

app/javascript/flavours/polyam/styles/homogay/diff.scss
Override in `status__content` needs to be kept, otherwise the color is wrong in toots.
=> Fix CW button color in notifications in homogay skin

app/serializers/manifest_serializer.rb
Ref #462 
Follow-up to 0c163659913f1d9d02cd8b5e45913846f2039c96
I don't want people to make the mistake of installing bad apps, so recommend Tusky instead.
=> Recommend Tusky as native app

.github/ISSUE_TEMPLATE/1.web_bug_report.yml, .github/ISSUE_TEMPLATE/2.server_bug_report.yml, .github/ISSUE_TEMPLATE/3.troubleshooting.yml, .github/ISSUE_TEMPLATE/4.feature_request.yml, .github/ISSUE_TEMPLATE/config.yml
The current templates don't work because they use an experimental key which is not permitted.
This disables the `type` key and reintroduces labels for categories.
Also changed the discussion link, since upstream's discussions aren't helpful.
=> Fix issue templates

app/javascript/flavours/glitch/styles/rich_text.scss
Upstream now styles these, so this is no longer needed
=> Remove old code block style from glitch flavour

app/javascript/flavours/polyam/styles/mastodon-light/variables.scss, app/javascript/flavours/polyam/styles/rich_text.scss, app/javascript/flavours/polyam/styles/variables.scss
Reverts additional changes from #741
I do actually prefer a bit of more color in the interface.
The highlight theme doesn't work in the light skin, unfortunately.
=> Revert rich text color overrides

app/javascript/flavours/polyam/features/compose/components/search.jsx
The controller now checks whether a search can be performed or not, so even when messing with the DOM, no search can be performed while logged out, which makes the dummy object obsolete.
This simplifies and reduces the conflict potential.
=> Remove dummy input for disabled search

app/javascript/flavours/polyam/features/notifications_v2/components/avatar_group.tsx, app/javascript/flavours/polyam/features/notifications_v2/components/displayed_name.tsx
I was hoping for upstream to address this, but this didn't happen.
This makes it easier to quickly copy the link to the account or open it in a new tab.
=> Use Permalink component in notification groups

app/javascript/flavours/polyam/features/notifications_v2/filter_bar.tsx
I actually have no idea how I missed this, but since grouped notifications were introduced, the filter for reactions was missing.
=> Re-add notification filter for reactions

app/javascript/flavours/polyam/features/onboarding/follows.tsx
Follow-up to #767 
There is probably a more proper fix, but this also works for now
=> Fix redirect to `/home` in onboarding in advanced interface

app/javascript/flavours/polyam/components/follow_icon_button.tsx
Follow-up to #767 
The FollowIconComponent didn't check whether own accountId is given and showed the follow icon instead of returning null.
=> Fix follow button being shown in compose

app/javascript/flavours/polyam/components/column_search_header.tsx
This component uses the form element, which by default tries to make a request or reload the page when pressing enter.
This action is thankfully denied by the CSP, but it resulted in an error in the console.
This change adds the missing `e.prevenDefault` to avoid this.
=> Fix ColumnSearchHeader creating CSP violation on enter

app/javascript/flavours/polyam/features/status/components/card.jsx
This is a boolean value which is falsy by default, so explicitly setting it to false is redundant.
Also support for defaultProps will be removed.
=> Remove unnecessary default prop in status card

app/javascript/flavours/polyam/styles/reset.scss
Interesting, the colors are wrong in Chromium browsers.
Or rather technically wrong in Firefox, but FF looks more correct.
Firefox uses the background-border-color as defined in the variables file, while Chromium uses it as defined in the skin file.
=> Fix missed change in port

app/javascript/flavours/polyam/components/follow_button.tsx, app/javascript/flavours/polyam/components/follow_icon_button.tsx, app/javascript/flavours/polyam/containers/account_container.jsx, app/javascript/flavours/polyam/features/account_timeline/containers/header_container.jsx, app/javascript/flavours/polyam/features/directory/components/account_card.tsx, app/javascript/flavours/polyam/initial_state.js, app/models/concerns/user/has_settings.rb, app/models/user_settings.rb, app/serializers/initial_state_serializer.rb, app/views/settings/preferences/appearance/show.html.haml
- 37ca59815cd3a3b2662e20f0c28185eb0d604dd4
I came around on this. I hate needless extra clicks, but I guess for potentially "destructive" changes like unfollowing it's fine.
=> Port removal of unfollow modal setting

app/javascript/flavours/polyam/styles/components/collapsing.scss, app/javascript/flavours/polyam/styles/components/index.scss, app/javascript/flavours/polyam/styles/components/notification.scss, app/javascript/flavours/polyam/styles/components/status/status.scss
Since upstream is dropping this feature, I think it makes sense to move it to a separate file.
=> Extract collapsing CSS to separate file

app/javascript/flavours/polyam/styles/homogay/diff.scss
Wraps the fix for scrollbar colors in Chromium in the new `.custom-scrollbars` class like upstream.
=> Wrap scrollbar fix in additional class in homogay

app/javascript/flavours/polyam/components/content_warning.tsx, app/javascript/flavours/polyam/components/media_icon.tsx, app/javascript/flavours/polyam/components/mentions_placeholder.jsx, app/javascript/flavours/polyam/components/status.jsx, app/javascript/flavours/polyam/components/status_content.jsx, app/javascript/flavours/polyam/components/status_icons.jsx, app/javascript/flavours/polyam/features/local_settings/page/index.jsx, app/javascript/flavours/polyam/features/status/components/detailed_status.tsx, app/javascript/flavours/polyam/reducers/local_settings.js, app/javascript/flavours/polyam/styles/components/collapsing.scss, app/javascript/flavours/polyam/styles/components/status/status.scss
Port change postponed in #798
- b7afca0f053a74518c2c0742907e8e4f7d92d709
Wraps content and media in a div, similar to before, but way simpler.
CWs are no longer collapsed, which I think is better.
=> Port status markup change

app/controllers/admin/reports/actions_controller.rb, app/controllers/admin/statuses_controller.rb, app/models/admin/status_batch_action.rb, app/views/admin/reports/_actions.html.haml, app/views/admin/reports/actions/preview.html.haml, config/locales-polyam/en.yml, spec/controllers/admin/reports/actions_controller_spec.rb
Ref #757 
This removes the ability to hide toots behind a warning as this feature sees barely any use and is a mess.
This does not change hidden toots or prevent appeals. This is just a first step in removing this feature.
=> Remove ability to resolve reports with hiding toots

app/javascript/flavours/polyam/components/alt_text_badge.tsx
The use of `useAppDispatch` prevented media from loading in server rendered pages. This fixes that by using store directly.
This makes media loading again, but clicking the badge just reloads the page. That issue is shared with upstream.
=> Fix media attachments not showing in server pages

app/javascript/flavours/polyam/components/alt_text_badge.tsx
Adds missing `type='button'` attribute, so clicking the badge doesn't act as submit in server-rendered pages.
=> Fix alt-badge acting as form submit

app/javascript/flavours/polyam/components/alt_text_badge.tsx, app/javascript/flavours/polyam/containers/status_container.js, app/javascript/flavours/polyam/features/account_gallery/index.jsx, app/javascript/flavours/polyam/features/status/index.jsx, app/javascript/flavours/polyam/features/ui/components/alttext_modal.tsx, app/javascript/flavours/polyam/features/ui/components/modal_root.jsx
Upstream intends to use the `AltTextModal` name for the focal point modal (the one to add alt-text), which will cause a name conflict.
This renames it to `AltTextDisplayModal` though I'm not too happy with that name.
I might change it to `ShowAltTextModal`
=> Rename alt-text modal component

app/views/admin/accounts/index.html.haml, app/views/admin/custom_emojis/index.html.haml, app/views/admin/instances/index.html.haml, app/views/admin/reports/index.html.haml, app/views/admin/tags/index.html.haml
Follow-up to #814 
This fixes the button width of buttons used in server-rendered pages
Before:
After:
=> Add missing `button--block` class to some buttons

app/javascript/flavours/polyam/styles/homogay/diff.scss
The higher radius looks off in the compose form, so set it to default 4px
=> Fix border radius of buttons in compose form in homogay

app/javascript/flavours/polyam/components/alt_text_badge.tsx, app/javascript/flavours/polyam/components/media_gallery.jsx, app/javascript/flavours/polyam/features/account_gallery/components/media_item.tsx
Fixes #815
I'm still not too fond of the overlay, but I can't think of a good solution to fix the issue.
Todo?:
- Audio and video attachments still use the modal, ~upstream doesn't show alt-text at all anymore afaik~.
Correction: The tooltip is still used for audio and video
=> Switch to upstream's overlay for alt-text of images

app/javascript/flavours/polyam/styles/homogay.scss, app/javascript/flavours/polyam/styles/homogay/css_variables.scss, app/javascript/flavours/polyam/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/variables.scss, app/javascript/skins/polyam/homogay/common.scss
Follow-up to #832 
Fixes deprecation warnings by using `use` instead of `import` in homogay files.
Fixes wrong colors due to upstream changes.
Simplifies color overrides.
=> Update homogay with new SCSS

app/javascript/flavours/polyam/styles/css_variables.scss
Follow-up to #585 
I don't know what caused the values to not apply correctly in skins, but they do now, so it doesn't make sense to keep using color-mix.
=> Change toot background values to match upstream

app/javascript/flavours/glitch/components/status_action_bar.jsx
Follow-up to #851
I'm certain I explicitly added that one back when resolving merge conflicts.
Anyway, this fixes the glitch flavour crashing.
(I'm actually confused how this passed lint/tests, since it should've given an error)
=> Re-add missing `maxReactions` import in glitch flavour

app/javascript/flavours/polyam/features/status/index.jsx
Follow-up to #865
I'm not sure whether this affects prod, but the wrong prop breaks detailed view in dev.
=> Fix wrong PropType in Status component

app/javascript/flavours/polyam/styles/components/media.scss
Follow-up to #867 
I mistyped the background value, which prevented the background color from applying.
=> Fix missing background in audio modal

app/javascript/flavours/polyam/features/audio/index.tsx
It's doing nothing in that context, so no point in showing it.
This also removes the button in reports, but that's in line with video attachments.
=> Don't show alt-button in audio modal

app/helpers/context_helper.rb, app/serializers/activitypub/emoji_reaction_serializer.rb
As far as I understand, some ActivityPub implementations cannot reliably handle emoji reactions without this context.
=> Cherry-pick context extension from upstream's reactions PR

app/javascript/flavours/polyam/components/account.tsx, app/javascript/flavours/polyam/features/onboarding/follows.tsx
This uses the `withBio` prop instead of `minimal` to add minimal class.
This aligns the code more with upstream and also no longer requires workarounds for the changed default, while preserving the minimal style.
=> Remove `minimal` override in Account component

app/javascript/flavours/polyam/components/follow_icon_button.tsx, app/javascript/flavours/polyam/styles/components/loading.scss
This adds a loading indicator to follow icons. This prevents items from "jumping" on load.
Not sure why this works now, but I'm not complaining.
(For context: I tried this initially and kept getting errors)
=> Add loading indicator to follow icon buttons

app/javascript/flavours/polyam/components/account.tsx
Closes #857
- 5d817a758d0d16924364489092f661b82451e1c9
- 24551375cf556dbf8ef86dd508413a1b449ebde9
- 6b066eac2c6fcf7b8073d0a0d27aa6a569a68f4a
Issues:
=> Port Add dropdown to lists of accounts in web UI

app/javascript/flavours/polyam/styles/components/notification.scss
Some tweaks for the grouped notifications UI.
This aligns the timestamp towards the end of the header and hides the header in mentions.
Before:
After:
(The reflow issue is difficult to capture in screenshots as it requires a changing timestamp)
=> Grouped notifications UI tweaks

app/javascript/flavours/polyam/features/ui/index.jsx
This re-adds the key combination for collapsing.
Not sure why this was removed.
Maybe accidentally while porting a change.
=> Re-add missing hotkey for toggling collapsing

app/javascript/flavours/polyam/styles/components/status/status.scss
This doesn't look as out-of-place as it used to and also matches the size in upcoming collapsed notifications.
=> Increase collapse icon size

app/javascript/flavours/polyam/features/notifications_v2/components/notification_group_with_status.tsx, app/javascript/flavours/polyam/styles/components/collapsing.scss
Considerations:
- Unread notifications should not be collapsed
- Hiding embedded status element is the most straightforward thing design-wise (I don't think gradients make sense here)
- Follow and other non-status notifications don't need collapsing
Unclear:
- Collapsing of notifications with CWs (As in, should they uncollapsed by default?). Not sure that's really possible as there is no way to know whether there is a CW at the time of collapsing.
TODO:
=> Add collapsing to notification groups

app/models/notification_group.rb, spec/requests/api/v2/notifications_spec.rb
Fixes #886
Dunno if this should be considered an API change, but `sample_account_ids`  and `count` no longer includes duplicates, although that was only ever a concern with reactions.
This changes the notification group query to exclude duplicate accounts which can happen when the same account adds multiple reactions.
=> Fix duplicate account IDs in notification group

db/migrate/20230517195218_polyam_set_exclusive_not_null.rb, db/migrate/20230517195554_polyam_validate_exclusive_not_null.rb
While testing switching between forks, I noticed that these migrations are run even on newer installs.
These migrations are only necessary when polyam-glitch was run before upstream implemented this feature.
=> Skip old exclusive lists migrations when running new code

db/migrate/20250606113926_polyam_remove_exclusive_check_constraint.rb, db/schema.rb
:warning: Includes DB migration
This constraint was only for compatibility with Postgres 10, but that version is no longer supported.
=> Remove obsolete check constraint for exclusive column

db/migrate/20221217125117_polyam_create_status_reactions.rb, db/migrate/20221218014608_polyam_change_status_reactions_table.rb, db/migrate/20230222143034_polyam_add_reactions_count.rb, db/post_migrate/20230222145758_polyam_backfill_reactions_count.rb
This should prevent name conflicts with upstream's PR, but does not solve the duplicate migration issue.
=> Add `Polyam` prefix to status reaction migrations

db/migrate/20221218014608_polyam_fix_status_reactions_foreign_keys.rb
Not necessary, but clearer on what the migration does.
Also I tested whether this migration runs if the correct keys already exist and turns out: yes.
That's not necessary, but it also does cause no harm.
(I was working on whether the migration can be skipped)
=> Rename foreign key migration for reactions

config/navigation.rb
This probably got accidentally removed during a refactor.
=> Restore navigation to request text filters

spec/requests/admin/registration_filters_spec.rb
Follow-up to #908 
Oops, wrote the path out, looked what the other specs did, noticed not much, and copy and pasted one, so I don't have to type that out, but that of course overwrote the path.
=> Fix path in registration filter spec

app/helpers/application_helper.rb, app/views/admin/roles/_form.html.haml
That method has been removed by upstream a while ago, but was still used for the role badge preview.
=> Replace `person_icon` with `material_symbol` call

app/helpers/application_helper.rb, app/views/admin/reports/_status.html.haml, app/views/admin/statuses/show.html.haml
Not sure what my reasoning was to set it to empty string instead, but I think 'custom' is clearer.
Sidenote:
Some FASP pages use the boost icon and I'm not sure why and how to best address that. It's on the bottom of my to-do list though.
=> Change variant from empty string to 'custom' for custom icons

lib/tasks/icons.rake
Adds a new rake task to check for presence of material icons in IconHelper and of FA icon files.
This is far better than trying to add specs (#931) as this allows extracting every used icon and therefore provide full coverage.
=> Add rake task to check icons

.github/workflows/check-icons.yml
Follow-up to #941 
Uses the `icons:check` rake task to check icons
=> Add workflow to check icons

lib/tasks/tootkeeper.rake
This is the [tootkeeper script](https://github.com/polyamspace/scripts/blob/main/toot_keeper.py) translated to ruby and implemented as a rake task to allow usage in workflows without having to set up python.
=> Add rake task to check locales for "post"

app/helpers/icon_helper.rb
Follow-up to #948 
In cases where `fa_icon` returns nil, because there is no default value for non-existing icons, that nil is passed to `fa_variant` which causes an error because `nil.to_sym` is undefined.
=> Fix crash when `nil` is passed to `fa_variant`
