polyamspace/mastodon

app/javascript/flavours/glitch/styles/components/accounts.scss, app/javascript/flavours/glitch/styles/components/status.scss, app/javascript/flavours/glitch/styles/mastodon-light.scss, app/javascript/flavours/glitch/styles/mastodon-light/diff.scss, stylelint.config.js
Last merge from upstream introduced new problems.
Also added `highlight.scss` to ignored files and fixed import in `mastodon-light.scss`
=> Fix more lint errors

app/controllers/api/v1/accounts/credentials_controller.rb, app/models/admin/status_batch_action.rb, app/models/concerns/omniauthable.rb, app/views/admin/reports/_actions.html.haml, app/views/admin/reports/show.html.haml, app/views/admin/settings/discovery/show.html.haml, app/views/layouts/mailer.html.haml, app/views/relationships/show.html.haml, config/locales/en.yml, config/locales/ko.yml, config/locales/simple_form.en.yml, lib/mastodon/accounts_cli.rb, spec/controllers/admin/reports/actions_controller_spec.rb
Conflicts:
- `views/admin/settings/discovery/show.html.haml`
New settings where old setting were.
Accepted both.
- `config/locales/simple-form.en.yml`
New string replaced "toot".
Accepting new strings while keeping "toot".
new lint error in `spec/controllers/admin/reports/actions_controller_spec.rb` can be ignored as no other spec file has the required comment, which looks intentional.
=> Merge upstream changes

app/controllers/api/v1/admin/trends/tags_controller.rb, app/javascript/flavours/glitch/components/admin/Trends.js, app/javascript/mastodon/components/admin/Trends.js
=> Fix admin trends using wrong serializer

app/javascript/flavours/glitch/actions/lists.js, app/javascript/flavours/glitch/features/list_editor/components/edit_list_form.js, app/javascript/flavours/glitch/features/list_editor/index.js, app/javascript/flavours/glitch/features/list_timeline/index.js, app/javascript/flavours/glitch/locales/en.json, app/javascript/flavours/glitch/reducers/list_editor.js, app/javascript/flavours/glitch/styles/components/index.scss, app/javascript/mastodon/actions/lists.js, app/javascript/mastodon/features/list_editor/components/edit_list_form.js, app/javascript/mastodon/features/list_editor/index.js, app/javascript/mastodon/features/list_timeline/index.js, app/javascript/mastodon/reducers/list_editor.js, app/javascript/styles/mastodon/components.scss
Follow up to #1
Removed setting from list editor and added it to column setting.
Was sitting on this for a while.
=> Convert exclusive setting to column setting

app/javascript/flavours/glitch/components/media_gallery.js, app/javascript/flavours/glitch/components/scrollable_list.js, app/javascript/flavours/glitch/components/status_action_bar.js, app/javascript/flavours/glitch/components/status_content.js, app/javascript/flavours/glitch/components/status_reactions.js, app/javascript/flavours/glitch/features/about/index.js, app/javascript/flavours/glitch/features/account_gallery/components/media_item.js, app/javascript/flavours/glitch/features/audio/index.js, app/javascript/flavours/glitch/features/privacy_policy/index.js, app/javascript/flavours/glitch/features/status/components/action_bar.js, app/javascript/flavours/glitch/features/status/components/detailed_status.js, app/javascript/flavours/glitch/features/status/index.js, app/javascript/flavours/glitch/features/video/index.js, app/javascript/mastodon/components/status_action_bar.js, app/javascript/mastodon/components/status_reactions.js, app/javascript/mastodon/features/about/index.js, app/javascript/mastodon/features/privacy_policy/index.js, app/javascript/mastodon/features/status/components/action_bar.js, app/javascript/mastodon/features/status/index.js
=> More lint fixes

app/views/settings/preferences/appearance/show.html.haml
Follow-up to #74 
Of course I missed the most obvious one
=> Add polyam_only label to reactions

app/javascript/flavours/glitch/styles/oatstodon/diff.scss
=> Oatstodon: Fix background change when hovering disabled buttons

app/javascript/flavours/glitch/styles/oatstodon/diff.scss
Ref #76 
Having these messes up the styling for some button, specifically disabled buttons, like the toot button or vote button on polls.
=> Oatstodon: Remove styling for buttons

.github/workflows/build-image.yml
Enable docker containers for polyam-glitch.
(I should stop having versioned branches...)
=> Enable docker builds

app/javascript/flavours/glitch/styles/components/status.scss, app/javascript/styles/mastodon/components.scss
Fixes misalignment of the reactions-bar when viewing threads.
=> Add margin to reactions-bar in thread view

app/controllers/api/v1/statuses/reactions_controller.rb, app/models/concerns/account_associations.rb, app/policies/status_policy.rb, app/services/react_service.rb, app/workers/unreact_worker.rb
Ref #21
This fixes an issue where it was possible for a blocked account to still react to a toot.
=> Fix being able to react to unauthorised toots

app/models/status_reaction.rb
Ref #21
Fixes an issue which made it possible to react with disabled custom_emojis
=> Prevent reactions with disabled emojis

app/controllers/api/v1/statuses/reactions_controller.rb
=> Fix malformed query in reactions controller

app/lib/activitypub/activity.rb, app/lib/activitypub/activity/emoji_react.rb, app/lib/activitypub/activity/like.rb, app/lib/activitypub/activity/undo.rb, app/models/concerns/account_interactions.rb, app/models/status.rb, app/models/status_reaction.rb, spec/lib/activitypub/activity/emoji_react_spec.rb, spec/lib/activitypub/activity/like_spec.rb, spec/lib/activitypub/activity/undo_spec.rb, spec/models/concerns/account_interactions_spec.rb, spec/models/status_reaction_spec.rb
Ref #21 
Didn't want to open a PR for each of these, as this would create a lot of workflow runs.
=> Fix more issues with reactions

app/lib/activitypub/activity.rb, app/lib/activitypub/activity/emoji_react.rb, app/lib/activitypub/activity/like.rb, app/lib/activitypub/activity/undo.rb, app/services/react_service.rb, spec/lib/activitypub/activity/emoji_react_spec.rb, spec/lib/activitypub/activity/like_spec.rb, spec/lib/activitypub/activity/undo_spec.rb
Ref #21
Some minor refactor
Additionally, prevent reacting with remote emojis when status is not local (Should've been included in the last PR)
=> Refactor emoji reactions

config/locales-glitch/de.yml
Follow-up to #138 
This permission doesn't exist anymore.
=> Remove translation for change_max_use

app/javascript/flavours/glitch/styles/oatstodon/diff.scss
Ref #76
Fixes a regression from fefdc3244cc53573e835009c17f9bc658386639e
=> Oatstodon: Fix wrong background for private mentions

app/javascript/flavours/glitch/styles/fairy-floss/variables.scss, app/javascript/flavours/glitch/styles/oatstodon/variables.scss
Ref #15 #76 
Changes the background colors for buttons back.
=> Fix button color regression in themes

app/javascript/flavours/glitch/styles/homogay.scss, app/javascript/flavours/glitch/styles/homogay/animations.scss, app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/glitch/styles/homogay/variables.scss, app/javascript/skins/glitch/homogay/common.scss, app/javascript/skins/glitch/homogay/names.yml
Stolen[^1] from [nyastodon](https://git.bsd.gay/fef/nyastodon), created by `anna@girldick.gay`
- d0186777c6546f623174d232b987146f4a9380f6
This is pretty much already ready to be merged, but there are some changes expected, so I'm not sure whether it makes sense.
[^1]: https://girldick.gay/@anna/110689804600509886
=> Add homogay theme

app/models/custom_emoji_filter.rb, app/views/admin/custom_emojis/index.html.haml, spec/models/custom_emoji_filter_spec.rb
Actually not sure how much sense "All" makes as a filter, but hey.
=> Add enabled/disabled filter to custom emojis

app/javascript/flavours/glitch/features/status/index.jsx
Reverts #188
This didn't really fix the issue this was introduced for and that issue seems to have been fixed upstream recently.
=> Remove refresh button from detailed status view

app/javascript/flavours/glitch/locales/en.json, config/locales/en.yml
Ref #23
Missed some of these again...
=> Fix missed "post" instead of "toot"

app/models/public_feed.rb, spec/models/public_feed_spec.rb
Reverts #233 
Yep, this is so expensive it prevents the timelines from loading.
=> Revert Hiding toots only interacted by muted accounts

package.json, yarn.lock
Ref #20 
Update from 11.7.0 to 11.9.0
=> Update highlight.js to 11.9.0

config/code-languages.yml
Ref #20 
This was created by a script automatically extracting valid languages from highlight.js itself.
Never trust docs.
=> Update valid code languages

app/javascript/flavours/glitch/reducers/compose.js
When editing a toot in threaded mode, it gets stuck in edit mode.
=> Fix threaded mode continuously editing same toot

app/javascript/flavours/glitch/reducers/compose.js
When editing a local-only toot while in threaded mode, an additional local-only emoji was added.
=> Fix editing in threaded mode adding additional local-only emoji

app/lib/advanced_text_formatter.rb, spec/lib/advanced_text_formatter_spec.rb
I should really create these before opening upstream PRs, so I don't have to wait...
=> Fix mentions being formatted with markdown

app/javascript/flavours/glitch/components/status_action_bar.jsx, app/javascript/mastodon/components/media_gallery.jsx, app/javascript/mastodon/components/status_action_bar.jsx, app/javascript/mastodon/features/about/index.jsx, app/javascript/mastodon/features/account/components/header.jsx, app/javascript/mastodon/features/getting_started/index.jsx, app/javascript/mastodon/features/privacy_policy/index.jsx, app/javascript/mastodon/features/ui/components/link_footer.jsx
This still leaves some changes, but they are rather self-contained and easier to resolve in case of a conflict.
=> Remove some modifications of vanilla flavour

app/javascript/flavours/glitch/components/media_gallery.jsx, app/javascript/flavours/glitch/components/status.jsx, app/javascript/flavours/glitch/features/account/components/header.jsx, app/javascript/flavours/glitch/features/account_timeline/components/limited_account_hint.jsx, app/javascript/flavours/glitch/features/compose/components/search.jsx, app/javascript/flavours/glitch/features/local_settings/page/item/index.jsx, app/javascript/flavours/glitch/features/ui/index.jsx
I was bored.
Fixes errors, which are only present in the dev env, so no functional changes.
It just reduces the noise and makes spotting issues easier.
I likely haven't caught them all yet.
Remaining issues:
- (search.jsx) Warning: validateDOMNesting(...): \<button\> cannot appear as a descendant of \<button\>.
It can and it does.
- (scrollable_list.jsx) Uncaught TypeError: can't access property "scrollHeight", this._getScrollingElement() is null
Not sure what is causing this. Happens sporadically when visiting account pages
- (account_gallery/index.jsx) Warning: Failed prop type: Required prop `attachments` was not specified in `AccountGallery`.
Not sure why.
- Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use …
=> Fix errors in dev

app/javascript/flavours/glitch/components/account.jsx, app/javascript/flavours/glitch/components/server_banner.jsx, app/javascript/flavours/glitch/features/about/index.jsx, app/javascript/flavours/glitch/styles/components/accounts.scss, app/javascript/flavours/glitch/styles/components/status.scss
Ports the account rows design change while keeping the current design of glitch-soc.
I rejected most of 0ddc89528213859bf4caeefd475a93ed973ab0e0
=> Port account rows design change

app/javascript/flavours/glitch/features/ui/components/confirmation_modal.jsx
=> Fix wrong attribute in confirmation modal

app/views/custom_css/show.css.erb
Changes the color intensity on badges.
Before:
After:
=> Change role badge color intensity

app/javascript/flavours/glitch/packs/public.jsx, app/views/admin/roles/_form.html.haml
Follow-up to #282
Changes the preview colors to match changes.
=> Adjust preview colors

app/javascript/flavours/glitch/features/status/components/card.jsx, app/javascript/flavours/glitch/styles/components/explore.scss, app/javascript/flavours/glitch/styles/components/misc.scss, app/javascript/flavours/glitch/styles/components/search.scss, app/javascript/flavours/glitch/styles/components/status.scss, app/javascript/flavours/glitch/styles/mastodon-light/diff.scss, app/javascript/flavours/glitch/styles/mastodon-light/variables.scss
This, unfortunately, isn't handled well by custom themes
Preview:
- 82d36d3db308c90be2660155ff8cfcf335900084
- 66d609f48d3251ba80bd81ebf22ad2f560eca07a (Decided to keep underline)
=> Port link preview design change

app/javascript/flavours/glitch/components/hashtag_bar.tsx
=> Fix missing key in Hashtag bar

.prettierignore, config/i18n-tasks.yml, config/initializers/locale.rb, config/locales-glitch/de.yml, config/locales-glitch/en.yml, config/locales-glitch/simple_form.de.yml, config/locales-glitch/simple_form.en.yml, config/locales-polyam/de.yml, config/locales-polyam/en.yml, config/locales-polyam/simple_form.de.yml, config/locales-polyam/simple_form.en.yml
Fixes #304 
Let's see if this works...
=> Move polyam-glitch backend locales to own files

app/javascript/flavours/polyam/components/boost.tsx, app/javascript/flavours/polyam/components/icon_button.tsx, app/javascript/flavours/polyam/components/status_action_bar.jsx, app/javascript/flavours/polyam/features/compose/components/action_bar.jsx, app/javascript/flavours/polyam/features/direct_timeline/components/conversation.jsx, app/javascript/flavours/polyam/features/status/components/action_bar.jsx, app/javascript/flavours/polyam/features/ui/components/zoomable_image.jsx, app/javascript/flavours/polyam/styles/components/accounts.scss, app/javascript/flavours/polyam/styles/components/misc.scss, app/javascript/flavours/polyam/styles/components/modal.scss
Follow-up to #323 
There are probably more, but some of these are upstream issues (technically the media modal icons too...)
=> Fix some icon sizes

README.md
Make it clearer what this project is about, provide instructions to nudge people to use it, add descriptions of features.
=> Rewrite ReadMe

app/javascript/flavours/polyam/styles/components/accounts.scss, app/javascript/flavours/polyam/styles/components/status.scss
=> Fix more icons

app/javascript/flavours/polyam/features/video/index.jsx, app/javascript/flavours/polyam/styles/components/accounts.scss, app/javascript/flavours/polyam/styles/components/announcements.scss, app/javascript/flavours/polyam/styles/components/columns.scss, app/javascript/flavours/polyam/styles/components/compose_form.scss, app/javascript/flavours/polyam/styles/components/misc.scss, app/javascript/flavours/polyam/styles/components/status.scss
Follow-up to #323 
I should really do a once-over and check all icon sizes instead of fixing the ones I notice being off.
I relied too much on upstream for sizes.
(Meaning I should restore the sizes of old icons, even if they are slightly bigger in some cases)
=> Fix even more icons

app/javascript/flavours/polyam/styles/components/local_settings.scss
Another follow-up to #323 
I'm starting to regret changing icons...
=> Fix icon size in local settings

app/lib/activitypub/activity/like.rb, app/lib/activitypub/activity/undo.rb, spec/lib/activitypub/activity/like_spec.rb, spec/lib/activitypub/activity/undo_spec.rb
Also check for content attribute in Misskey likes as some Misskey forks omit `_misskey_reaction`
=> Check content attribute for Misskey likes

public/robots.txt
List of user agents from https://darkvisitors.com/
=> Disallow more data thieves by default

app/controllers/concerns/signature_verification.rb, app/lib/request.rb, spec/requests/signature_verification_spec.rb
Early merge
Improves Federation with GTS
=> Fix incorrect processing of http signatures

app/javascript/flavours/polyam/features/compose/components/header.jsx, app/javascript/flavours/polyam/styles/components/accounts.scss, app/javascript/flavours/polyam/styles/components/compose_form.scss, app/javascript/flavours/polyam/styles/components/drawer.scss, app/javascript/flavours/polyam/styles/components/misc.scss, app/javascript/flavours/polyam/styles/components/status.scss
Missed some code changes in the icon change due to noise. Ported these.
Made changes to closer match upstreams CSS and added comments to polyam changes to better keep track.
This isn't really done, but I've been dreading this all day.
=> Match upstream SCSS closer

app/javascript/flavours/polyam/styles/accessibility.scss, app/javascript/flavours/polyam/styles/components/accounts.scss, app/javascript/flavours/polyam/styles/components/announcements.scss, app/javascript/flavours/polyam/styles/components/columns.scss, app/javascript/flavours/polyam/styles/components/compose_form.scss, app/javascript/flavours/polyam/styles/components/explore.scss, app/javascript/flavours/polyam/styles/components/local_settings.scss, app/javascript/flavours/polyam/styles/components/media.scss, app/javascript/flavours/polyam/styles/components/misc.scss, app/javascript/flavours/polyam/styles/components/modal.scss
Follow-up to #384 
Added more comments, made it clearer they're for polyam-glitch and removed obsolete comments.
Took some more missed changes from upstream
=> Match upstream CSS further

config/locales-polyam/en.yml
Follow-up to #73 
Gawd damn, I'm really overworked.
How that happened and how I missed that for so long is beyond me.
=> Fix typos in allow sensitive media to trend setting description

app/controllers/api/v1/statuses/reactions_controller.rb, app/models/status.rb, app/services/react_service.rb, app/services/unreact_service.rb, spec/validators/status_reaction_validator_spec.rb
Cherry-picked the refactors from the upstream PR.
Would've had to do these anyway, so thanks.
I'm not too eager on the other changes. These will be merged when upstream does.
=> Cherry-pick changes from upstream reaction PR

app/javascript/flavours/polyam/features/compose/components/autosuggest_account.jsx, app/javascript/flavours/polyam/features/compose/components/navigation_bar.jsx, app/javascript/flavours/polyam/features/compose/components/search_results.jsx, app/javascript/flavours/polyam/features/compose/containers/compose_form_container.js, app/javascript/flavours/polyam/features/ui/index.jsx, app/javascript/flavours/polyam/reducers/meta.js, app/javascript/flavours/polyam/styles/_mixins.scss, app/javascript/flavours/polyam/styles/components/about.scss, app/javascript/flavours/polyam/styles/components/accounts.scss, app/javascript/flavours/polyam/styles/components/columns.scss, app/javascript/flavours/polyam/styles/components/compose_form.scss, app/javascript/flavours/polyam/styles/components/drawer.scss, app/javascript/flavours/polyam/styles/components/emoji_picker.scss, app/javascript/flavours/polyam/styles/components/explore.scss, app/javascript/flavours/polyam/styles/components/lists.scss, app/javascript/flavours/polyam/styles/components/media.scss, app/javascript/flavours/polyam/styles/components/misc.scss, app/javascript/flavours/polyam/styles/components/modal.scss, app/javascript/flavours/polyam/styles/components/search.scss, app/javascript/flavours/polyam/styles/components/sensitive.scss, app/javascript/flavours/polyam/styles/components/single_column.scss, app/javascript/flavours/polyam/styles/components/status.scss
Applies the upstream refactor, but keeps split scss files.
Also moved some classes to imo more appropriate files.
=> Refactor and reduce differences in SCSS like glitch-soc

app/javascript/flavours/glitch/styles/oatstodon/diff.scss, app/javascript/flavours/polyam/styles/oatstodon/diff.scss
The CSS refactor introduced new borders which this removes.
=> Remove additional borders from Oatstodon theme

app/javascript/flavours/glitch/styles/oatstodon/diff.scss, app/javascript/flavours/polyam/styles/oatstodon/diff.scss
Due to the CSS refactor this class no longer applied.
=> Fix compose suggestions colors in Oatstodon theme

app/javascript/flavours/polyam/features/account/components/header.jsx, app/javascript/flavours/polyam/styles/components/accounts.scss, app/javascript/flavours/polyam/styles/components/status.scss
Added some extra changes like keeping fields hidden when empty and joined date at the bottom of profiles.
This unfortunately again messes up themes
=>  Port upstream's design adoption of profiles

app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/diff.scss
Changes the color to the default color, which makes it more distinct and readable
=> Fix color of profile fields content in homogay theme

app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/diff.scss
Keeps background color before #426
=> keep profile background color in homogay theme

app/javascript/flavours/glitch/styles/oatstodon/diff.scss, app/javascript/flavours/polyam/styles/oatstodon/diff.scss
Background now needs to be applied to header class directly
Also account-note textarea focus.
Also removes new border below header image.
=> Fix background of profiles in Oatstodon

app/javascript/flavours/polyam/components/collapse_button.jsx, app/javascript/flavours/polyam/components/display_name.tsx, app/javascript/flavours/polyam/components/status.jsx, app/javascript/flavours/polyam/components/status_header.tsx, app/javascript/flavours/polyam/components/status_icons.jsx, app/javascript/flavours/polyam/components/status_prepend.jsx, app/javascript/flavours/polyam/features/account_timeline/components/moved_note.jsx, app/javascript/flavours/polyam/features/notifications/components/admin_report.jsx, app/javascript/flavours/polyam/features/notifications/components/admin_signup.jsx, app/javascript/flavours/polyam/features/notifications/components/follow.jsx, app/javascript/flavours/polyam/features/notifications/components/follow_request.jsx, app/javascript/flavours/polyam/features/notifications/components/setting_toggle.jsx, app/javascript/flavours/polyam/features/ui/components/boost_modal.jsx, app/javascript/flavours/polyam/features/ui/components/favourite_modal.jsx, app/javascript/flavours/polyam/styles/components/accounts.scss, app/javascript/flavours/polyam/styles/components/buttons.scss, app/javascript/flavours/polyam/styles/components/columns.scss, app/javascript/flavours/polyam/styles/components/compose_form.scss, app/javascript/flavours/polyam/styles/components/drawer.scss, app/javascript/flavours/polyam/styles/components/dropdown.scss, app/javascript/flavours/polyam/styles/components/media.scss, app/javascript/flavours/polyam/styles/components/misc.scss, app/javascript/flavours/polyam/styles/components/modal.scss, app/javascript/flavours/polyam/styles/components/notification.scss, app/javascript/flavours/polyam/styles/components/single_column.scss, app/javascript/flavours/polyam/styles/components/status.scss
Not a fan of the missing icons in notifications.
=> Port further reduction of CSS and markup differences with upstream

app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/diff.scss
Due to refactor, most overrides didn't apply anymore
This is very sloppy with the focus of getting something workable instead of good.
=> Somewhat fix compose in homogay

app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/diff.scss
Remove obsolete classes and add new ones to preserve style.
Remove removed composer classes.
Remove obsolete overrides for emoji picker as it's dark themed now.
Remove obsolete overrides for polls.
Remove overrides for dropdown.
Fix color of wave at bottom
Fix border radius of drawer header
=> Fix compose properly in homogay

app/javascript/flavours/glitch/styles/backgrounds.scss, app/javascript/flavours/polyam/features/about/index.jsx, app/javascript/flavours/polyam/features/compose/components/search_results.jsx, app/javascript/flavours/polyam/styles/about.scss, app/javascript/flavours/polyam/styles/admin.scss, app/javascript/flavours/polyam/styles/backgrounds.scss, app/javascript/flavours/polyam/styles/basics.scss, app/javascript/flavours/polyam/styles/components/_mixins.scss, app/javascript/flavours/polyam/styles/components/about.scss, app/javascript/flavours/polyam/styles/components/accounts.scss, app/javascript/flavours/polyam/styles/components/columns.scss, app/javascript/flavours/polyam/styles/components/compose_form.scss, app/javascript/flavours/polyam/styles/components/conversation.scss, app/javascript/flavours/polyam/styles/components/directory.scss, app/javascript/flavours/polyam/styles/components/domains.scss, app/javascript/flavours/polyam/styles/components/drawer.scss, app/javascript/flavours/polyam/styles/components/dropdown.scss, app/javascript/flavours/polyam/styles/components/explore.scss, app/javascript/flavours/polyam/styles/components/lists.scss, app/javascript/flavours/polyam/styles/components/media.scss, app/javascript/flavours/polyam/styles/components/misc.scss, app/javascript/flavours/polyam/styles/components/notification.scss, app/javascript/flavours/polyam/styles/components/privacy_policy.scss, app/javascript/flavours/polyam/styles/components/regeneration_indicator.scss, app/javascript/flavours/polyam/styles/components/search.scss, app/javascript/flavours/polyam/styles/components/single_column.scss, app/javascript/flavours/polyam/styles/components/status.scss, app/javascript/flavours/polyam/styles/mastodon-light/diff.scss, app/javascript/flavours/polyam/styles/mastodon-light/variables.scss, app/javascript/flavours/polyam/styles/variables.scss
Fixes #468 
- 5b60d4b696cd5fd58ca77eca3365c2a0761c0f57
- 369e72853639ab23e1eef5d71734e00bca568bb9
- 1e1d97a78727570bb3343aa4008b93edae3dde1d
- 07cbae7a326ecba163b5e899f1ca5b9ae3d00a7d
=> Port background removal

app/javascript/flavours/glitch/styles/homogay.scss, app/javascript/flavours/polyam/styles/homogay.scss
=> Fix background colors in homogay

app/javascript/flavours/glitch/styles/fairy-floss.scss, app/javascript/flavours/glitch/styles/fairy-floss/diff.scss, app/javascript/flavours/polyam/styles/fairy-floss.scss, app/javascript/flavours/polyam/styles/fairy-floss/diff.scss
=> Fix background colors in FairyFloss

app/javascript/flavours/glitch/styles/oatstodon.scss, app/javascript/flavours/glitch/styles/oatstodon/diff.scss, app/javascript/flavours/polyam/styles/oatstodon.scss, app/javascript/flavours/polyam/styles/oatstodon/diff.scss
=> Fix background colors in oatstodon

app/javascript/flavours/glitch/styles/admin.scss, app/javascript/flavours/polyam/styles/admin.scss, app/views/admin/roles/_form.html.haml
Updates backgrounds of previews, since no background is applied to user profiles anymore.
Adds domain to preview if flavour isn't polyam.
=> Update backgrounds and add domain in badge preview

app/javascript/flavours/glitch/styles/homogay.scss, app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/glitch/styles/homogay/variables.scss, app/javascript/flavours/polyam/styles/homogay.scss, app/javascript/flavours/polyam/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/variables.scss
Updates homogay to the new monocolor design.
I must admit, I do like it a lot.
Also removes some dead overrides and cleans up the diff.
Before:
After:
=> Update homogay to new design

app/javascript/flavours/polyam/components/column_header.jsx, app/javascript/flavours/polyam/components/status_content.jsx, app/javascript/flavours/polyam/components/status_icons.jsx, app/javascript/flavours/polyam/features/about/index.jsx, app/javascript/flavours/polyam/features/account/components/action_bar.jsx, app/javascript/flavours/polyam/features/account/components/follow_request_note.jsx, app/javascript/flavours/polyam/features/audio/index.jsx, app/javascript/flavours/polyam/features/compose/components/search_results.jsx, app/javascript/flavours/polyam/features/explore/results.jsx, app/javascript/flavours/polyam/features/filters/select_filter.jsx, app/javascript/flavours/polyam/features/list_adder/components/list.jsx, app/javascript/flavours/polyam/features/local_settings/navigation/item/index.jsx, app/javascript/flavours/polyam/features/notifications/components/admin_report.jsx, app/javascript/flavours/polyam/features/notifications/components/admin_signup.jsx, app/javascript/flavours/polyam/features/notifications/components/filter_bar.jsx, app/javascript/flavours/polyam/features/notifications/components/follow.jsx, app/javascript/flavours/polyam/features/notifications/components/follow_request.jsx, app/javascript/flavours/polyam/features/ui/components/column_link.jsx, app/javascript/flavours/polyam/features/ui/components/media_modal.jsx, app/javascript/flavours/polyam/features/video/index.jsx
=> Remove obsolete `fixedwidth` attribute from components

app/javascript/flavours/glitch/components/status.jsx, app/javascript/flavours/glitch/features/ui/util/identity_consumer.jsx, app/javascript/flavours/polyam/components/status.jsx, app/javascript/flavours/polyam/features/ui/util/identity_consumer.jsx
Fixes #488 
Uses the fix from the upstream PR.
=> Fix media not hidden in notification requests

app/javascript/flavours/polyam/components/column_header.jsx, app/javascript/flavours/polyam/features/follow_requests/index.jsx
- 30483d618f94ed85ac90c78ae24fc40349891208
- be52633ee4ce4a14b48f82156cf64c0a3eb9835b
Currently not merged, because this makes navigating the advanced UI quite annoying.
=> Port back button appearing in column header unexpectedly

app/controllers/concerns/theming_concern.rb
I'm not sure this does or fix anything as everything seems to work correctly
=> Add polyam flavour to `current_flavour` in theming concern

app/javascript/flavours/polyam/features/onboarding/profile.jsx
=> Change onboarding to use server-provided character limits

app/javascript/flavours/polyam/features/notifications/components/follow_request.jsx
=> Fix follow request notification design

app/javascript/flavours/polyam/actions/announcements.js, app/javascript/flavours/polyam/actions/blocks.js
Follow-up to #562
Fixes botched search and replace in 93c508af2148f85d9f65e82274fe75c1502dd0f3
=> Fix botched search and replace during port

app/javascript/flavours/polyam/features/hashtag_timeline/components/column_settings.jsx, app/javascript/flavours/polyam/initial_state.js
Follow up to #405
- 541cbdd96319ad968d7fe7c85f0cb43e8c757d99
=> Port missed frontend changes for hashtag env var

app/javascript/flavours/polyam/styles/components/status.scss, app/javascript/flavours/polyam/styles/mastodon-light/diff.scss
Gradients have been broken for a while and I'm not sure upstream is going to fix that.
=> Fix gradients for collapsed toots

app/javascript/flavours/polyam/styles/components/status.scss, app/javascript/flavours/polyam/styles/mastodon-light/diff.scss, app/javascript/flavours/polyam/styles/mastodon-light/variables.scss, app/javascript/flavours/polyam/styles/variables.scss
Follow-up to #581
This should work with every reasonable up-to-date browser.
=> Add CSS var for toot backgrounds

app/javascript/flavours/glitch/components/admin/Trends.jsx, app/javascript/flavours/glitch/components/status_action_bar.jsx, app/javascript/flavours/glitch/components/status_icons.jsx, app/javascript/flavours/glitch/entrypoints/common.js, app/javascript/flavours/glitch/entrypoints/public.tsx, app/javascript/flavours/glitch/features/account/components/header.jsx, app/javascript/flavours/glitch/features/getting_started_misc/index.jsx, app/javascript/flavours/glitch/features/list_editor/components/edit_list_form.jsx, app/javascript/flavours/glitch/features/list_timeline/index.jsx, app/javascript/flavours/glitch/features/status/components/action_bar.jsx, app/javascript/flavours/glitch/features/ui/containers/status_list_container.js, app/javascript/flavours/glitch/styles/accounts.scss, app/javascript/flavours/glitch/styles/admin.scss, app/javascript/flavours/glitch/styles/mastodon-light/variables.scss, app/javascript/flavours/glitch/utils/backend_links.js
Reduce differences of polyam-glitch's glitch flavour with upstream
Overview:
- Removes dead role badge preview code and style
- Removes obsolete strings and props
- Removes `instanceAdminLink`
- Semantic changes (new lines, style order etc.)
=> Reduce differences in glitch flavour

app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/polyam/styles/homogay/diff.scss
=> Fix background of alt-text-modal in homogay

app/javascript/flavours/glitch/styles/fairy-floss/diff.scss, app/javascript/flavours/polyam/styles/fairy-floss/diff.scss
=> Fix background of alt-text-modal in FairyFloss

app/javascript/flavours/polyam/features/ui/index.jsx
I'm still not convinced this is polished enough, but seems useful for the simple UI.
Problems:
- The field name and value are misaligned which is mostly noticeable on long values
- User added notes are not shown
=> Enable hover cards

app/javascript/flavours/polyam/api_types/notifications.ts, app/javascript/flavours/polyam/features/notifications_v2/components/embedded_status.tsx, app/javascript/flavours/polyam/features/notifications_v2/components/notification_group.tsx, app/javascript/flavours/polyam/features/notifications_v2/components/notification_reaction.tsx, app/javascript/flavours/polyam/models/notification_group.ts, app/serializers/rest/notification_group_serializer.rb, app/services/notify_service.rb
=> Add grouped notifications for reactions

app/javascript/flavours/polyam/features/notifications/components/column_settings.jsx, app/javascript/flavours/polyam/styles/components/notification.scss
=> Grouped notification improvements

app/javascript/flavours/polyam/components/status.jsx, app/javascript/flavours/polyam/components/status_reactions.jsx, app/javascript/flavours/polyam/features/notifications_v2/components/embedded_status.tsx, app/javascript/flavours/polyam/features/status/components/detailed_status.jsx
This modernises the emoji reaction code and prepares for typescript conversion.
=> Refactor emoji reactions frontend code

app/javascript/flavours/polyam/styles/fairy-floss/diff.scss, app/javascript/flavours/polyam/styles/fairy-floss/variables.scss
=> Update FairyFloss to new admin UI

app/javascript/flavours/polyam/styles/homogay/diff.scss
Follow-up to #640 
Changes input, select and textarea elements to have darker background.
=> Change backgrounds of inputs in admin UI in homogay

app/javascript/flavours/glitch/api_types/notifications.ts, app/javascript/flavours/glitch/components/status.jsx, app/javascript/flavours/glitch/components/status_reactions.jsx, app/javascript/flavours/glitch/features/notifications_v2/components/embedded_status.tsx, app/javascript/flavours/glitch/features/notifications_v2/components/notification_group.tsx, app/javascript/flavours/glitch/features/notifications_v2/components/notification_reaction.tsx, app/javascript/flavours/glitch/features/status/components/detailed_status.jsx, app/javascript/flavours/glitch/models/notification_group.ts, app/javascript/flavours/glitch/styles/components.scss, app/javascript/flavours/glitch/styles/fairy-floss/diff.scss, app/javascript/flavours/glitch/styles/fairy-floss/variables.scss, app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/glitch/styles/homogay/variables.scss
Ports the following changes to glitch flavour:
- 0e2a7d457cb946ae7d8c99cc5ca8e03022755ebd
- 078114c54bb8af3a3ccccfd5f8f41a8c557dcdea (reactions-bar margin)
- 39290d4e7ce63b0d1020e3b7ce5198d736baa700
- 6441457e31bd8793a0504767c540b93b14cf6623
- 7954f81d894d5925cc077780312cc3201efb8d90
- 7db119be1a056694663b3263faf333954f2e3715
- d53b129e6005b6735dec0e92548e5cd4ca65e335
- c8d3ed6b33c348f53778f24b6cf8c4db9a76cfce (Follow-up to 7954f81d894d5925cc077780312cc3201efb8d90)
- c43ae473bcf48a29af6dcf180c24cd3448a081f3
=> Port to glitch flavour

app/javascript/flavours/glitch/components/status_action_bar.jsx, app/javascript/flavours/glitch/components/status_prepend.jsx, app/javascript/flavours/glitch/features/compose/components/emoji_picker_dropdown.jsx, app/javascript/flavours/glitch/features/notifications/components/filter_bar.jsx, app/javascript/flavours/glitch/features/notifications_v2/components/notification_reaction.tsx, app/javascript/flavours/glitch/features/reactions/index.jsx, app/javascript/flavours/glitch/features/status/components/action_bar.jsx, app/javascript/flavours/glitch/styles/components.scss
Reduces difference in emoji react code with polyam flavour.
I originally intended to work on the emoji react feature in the polyam flavour and just periodically merge the upstream PR for the glitch flavour, but some of the changes in the upstream PR are puzzling and I like my own code better.
=> Reduce differences in reactions code with polyam flavour

app/javascript/flavours/polyam/containers/account_container.jsx
Fixes #681 
`COMFIRM_UNFOLLOW` -> `CONFIRM_UNFOLLOW`
=> Fix typo in account container

app/javascript/flavours/polyam/styles/components/columns.scss, app/javascript/flavours/polyam/styles/components/misc.scss, app/javascript/flavours/polyam/styles/mastodon-light/diff.scss, app/javascript/flavours/polyam/styles/reset.scss
The first commit messed up the colors badly, but the second one fixes that and it looks alright.
- 7d4b602cb28675da01df6ae27faacff8d70c1711
- 2f01f5f4ea886c4a1bec2148d0ca82da5ae67f0c
=> Port scrollbar changes

app/javascript/flavours/polyam/features/notifications_v2/components/notification_with_status.tsx
Fixes #705
Seems like I missed this change in 6ec0e9da1e46f36044b551bd4768a023eec09fad
=> Add missing `unfocusable` attribute to NotificationWithStatus

app/javascript/flavours/polyam/components/alt_text_badge.tsx, app/javascript/flavours/polyam/components/media_gallery.jsx, app/javascript/flavours/polyam/features/account_gallery/components/media_item.tsx, app/javascript/flavours/polyam/styles/components/media.scss
Follow-up to #714 
Keeps using a modal instead of overlay
- a04433f995099854c06fbc7d02245a7d2a3677c0
=> Port clickable alt badge

app/javascript/flavours/polyam/styles/homogay/variables.scss
No idea how upstream's value relates to the other colors, so I just picked a random one that didn't distract too much.
=> Use different magic number for media outline in homogay

app/javascript/flavours/glitch/features/notifications_v2/filter_bar.tsx, app/javascript/flavours/glitch/features/ui/index.jsx, app/javascript/flavours/polyam/features/notifications_v2/filter_bar.tsx, app/javascript/flavours/polyam/features/ui/index.jsx
- 9ee86a738e9dddc0f89e496b4093af81b704b1a0
- 93fa102f9abcea8ac0e72afda562a537c4d21fd8
=> Merge upstream changes (stable-4.3)

config/navigation.rb
Re-applies #712 
Got accidentally removed during a merge conflict.
=> Re-apply "Default to "all" in `/admin/instances`"

config/navigation.rb
Re-applies #712 
Got accidentally removed during a merge.
=> Re-apply "Default to "all" in `/admin/instances`

app/javascript/flavours/polyam/styles/mastodon-light/variables.scss, app/javascript/flavours/polyam/styles/rich_text.scss, app/javascript/flavours/polyam/styles/variables.scss
- d11231a420cf80c3f924233d398002639cac0f8b
Changed color values to the previously used ones, since upstream's don't work with syntax highlighting.
=> Port rich text design change

app/javascript/flavours/glitch/features/compose/components/search.jsx, app/javascript/flavours/polyam/features/compose/components/search.jsx, app/javascript/flavours/polyam/locales/en.json, app/javascript/mastodon/features/compose/components/search.jsx
=> Change placeholder text of disabled search input

app/javascript/flavours/polyam/components/status_header.tsx
Status is still not correctly typed, but this prepares for when it is.
=> Resolve ToDo in status header

app/lib/advanced_text_formatter.rb, spec/lib/advanced_text_formatter_spec.rb
Same fix as #253 but also with hashtags and custom emojis
=> Fix hashtags and custom emoji being formatted with markdown

app/javascript/flavours/polyam/styles/components/column_settings.scss, app/javascript/flavours/polyam/styles/components/columns.scss
Some style files are rather large and some class names don't exactly match their file.
This results in having to search for class names rather than knowing where they are.
This PR has the following goals:
- Split large files into smaller files
- Move styles into more appropriate places
=> Another CSS refactor

app/javascript/flavours/polyam/features/account/components/header.jsx, app/javascript/flavours/polyam/styles/components/accounts/accounts.scss
Fixes #469 
- 19efa1b9f1486ffe95c14582017d9e9ede48d597
I vaguely remember this having a follow-up, but I couldn't find a commit.
Maybe I ported that already or I'm confusing this with the share button.
=> Port account button order change

app/javascript/flavours/polyam/styles/homogay/diff.scss
Upstream refactored components and styles resulting in some homogay styles being redundant or obsolete.
=> Remove unnecessary styles from homogay

app/javascript/flavours/polyam/styles/fairy-floss.scss, app/javascript/flavours/polyam/styles/fairy-floss/css_variables.scss, app/javascript/flavours/polyam/styles/fairy-floss/diff.scss, app/javascript/flavours/polyam/styles/fairy-floss/variables.scss, app/javascript/skins/polyam/fairy-floss/common.scss
=> Update FairyFloss with new SCSS

app/javascript/flavours/glitch/styles/fairy-floss.scss, app/javascript/flavours/glitch/styles/fairy-floss/css_variables.scss, app/javascript/flavours/glitch/styles/fairy-floss/diff.scss, app/javascript/flavours/glitch/styles/fairy-floss/variables.scss, app/javascript/flavours/glitch/styles/homogay.scss, app/javascript/flavours/glitch/styles/homogay/css_variables.scss, app/javascript/flavours/glitch/styles/homogay/diff.scss, app/javascript/flavours/glitch/styles/homogay/variables.scss, app/javascript/skins/glitch/fairy-floss/common.scss, app/javascript/skins/glitch/homogay/common.scss
- 6f769d651d3d53aae4be129d945eeaba99017396
- ee0cf8c9acfc21c39bcf4fc91ac9626528281f4e
Also some misc previously unported changes.
=> Port skin changes to glitch flavour

app/javascript/flavours/polyam/styles/homogay/variables.scss
Follow-up to #833 
Accidentally removed 2 vars in the mentioned PR.
This restores them.
=> Restore accidentally removed variables in homogay

app/javascript/flavours/polyam/styles/homogay/css_variables.scss
Values are correctly applied from the default skin.
=> Remove toot background CSS var in homogay

app/javascript/flavours/glitch/features/compose/containers/compose_form_container.js, app/javascript/flavours/glitch/features/local_settings/page/index.jsx, app/javascript/flavours/glitch/features/ui/index.jsx, app/javascript/flavours/glitch/locales/en.json, app/javascript/flavours/glitch/reducers/local_settings.js, app/javascript/flavours/glitch/styles/components.scss, app/javascript/flavours/glitch/theme.yml, app/javascript/flavours/polyam/features/compose/containers/compose_form_container.js, app/javascript/flavours/polyam/features/local_settings/page/index.jsx, app/javascript/flavours/polyam/features/ui/index.jsx, app/javascript/flavours/polyam/reducers/local_settings.js, app/javascript/flavours/polyam/styles/components/columns.scss, app/javascript/flavours/polyam/theme.yml, config/webpack/configuration.js
Conflicts:
- `config/webpack/configuration.js`
Upstream made change close to a polyam-glitch change.
Applied upstream change.
- dd3b51c9443e5686d84279fbda59d99dcc1e4ba0
- 0f2407b4c6886db8247d237848aab4351b007eb5
- 3a67407be9c8345474799f8f4557251d64d4bd54
=> Merge upstream up to '3a67407be9c8345474799f8f4557251d64d4bd54'

app/javascript/flavours/polyam/features/audio/index.tsx, app/javascript/flavours/polyam/styles/components/media.scss
- Moves "hide" button to corner like in other attachments
- Removes the container hiding certain elements in advanced UI
=> Fix some issues with new audio player

app/models/user_settings.rb
For the type of people polyam-glitch is aimed at, this makes more sense and this is a controversial feature.
=> Change default quote policy to "followers"

app/javascript/flavours/polyam/styles/components/accounts/accounts.scss
Upstream made the same mistake of setting a background color again...
=> Fix transparent avatars

app/javascript/flavours/glitch/locales/load_locale.ts, app/javascript/flavours/polyam/locales/load_locale.ts, config/environments/production.rb, config/environments/test.rb, db/post_migrate/20240307180905_migrate_devise_two_factor_secrets.rb, lib/premailer_bundled_asset_strategy.rb, package.json, yarn.lock
- 56b37268997acde2825d81b24e059e8199ed8a09
=> Merge upstream up to 'a4defbb2715d1dc8dc06b9f97625b2e6a3a5fa12'

app/javascript/flavours/polyam/components/follow_icon_button.tsx
=> Add edit button to follow icons

app/javascript/flavours/polyam/styles/components/notification.scss
=> Grouped notifications UI tweaks

README.md
=> Improve instructions in ReadMe

.rubocop_todo.yml, spec/models/registration_filter_spec.rb
Adds validation specs as there isn't really anything else to do.
I don't know how to test the second validation though.
=> Fix `RSpec/EmptyExampleGroup` in registration filter

app/javascript/flavours/polyam/features/ui/containers/status_list_container.js
Follow-up to #910
Messed this up in the port
=> Fix wrong condition for filtering replies

app/javascript/flavours/polyam/features/ui/containers/status_list_container.js
Follow-up to #910 
This one is on upstream.
=> Fix wrong condition for regex filtering

app/helpers/application_helper.rb, app/views/admin/reports/_status.html.haml, app/views/admin/statuses/show.html.haml
Backport of #935 
Not really necessary to backport, but I want the icon stuff to match to avoid problems later
=> Change variant from empty string to 'custom' for custom icons

lib/tasks/icons.rake
=> Add rake task to check icons

app/helpers/application_helper.rb, app/helpers/icon_helper.rb, app/views/admin/custom_emojis/index.html.haml, app/views/admin/reports/_status.html.haml, app/views/admin/status_edits/_status_edit.html.haml, app/views/admin/statuses/show.html.haml, app/views/filters/statuses/_status_filter.html.haml, config/navigation.rb, lib/tasks/icons.rake
=> Add icon variant detection from name

config/locales/simple_form.en-GB.yml
=> Fix "post" in en-GB locale

CHANGELOG.md, app/javascript/flavours/polyam/features/picture_in_picture/components/footer.tsx, app/javascript/mastodon/features/picture_in_picture/components/footer.tsx, config/cache_buster.yml, config/email.yml, config/initializers/settings_digests.rb, config/mastodon.yml, config/translation.yml, config/vapid.yml, db/migrate/20241014010506_remove_duplicate_indexes.rb, docker-compose.yml, lib/mastodon/version.rb, spec/configuration/email_spec.rb, vite.config.mts
Conflicts:
- `config/mastodon.yml`
Upstream changed lines which were modified.
Applied upstream modification.
- 81b363b338527b610c19e002b47288b16c13298c
=> Merge upstream changes (stable-4.4)

app/helpers/icon_helper.rb
=> Fix crash when `nil` is passed to `fa_variant`
